// Package header owns the comment at the top of a muxt-generated file: the
// command line that produced it and, when recorded, the muxt version.
package header

import (
	"bufio"
	"errors"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"strings"
)

const (
	prefix        = "// Code generated by muxt generate "
	suffix        = ". DO NOT EDIT."
	versionPrefix = "// muxt version: "

	byteOrderMark = string(rune(0xFEFF)) // the UTF-8 byte order mark
	whitespace    = " \t\r\n"
)

// Header is what a generated file's header records.
type Header struct {
	// Command is the text between "muxt generate " and the ". DO NOT EDIT."
	// suffix: the arguments joined by single spaces.
	Command string
	// Version is empty when the file records none.
	Version string
}

// Args returns the arguments of the command that generated the file.
func (h Header) Args() []string {
	return strings.Fields(h.Command)
}

// Format returns the header of a file generated with args, including the
// trailing blank line that keeps it out of the package doc comment.
func Format(args []string, version string) string {
	var sb strings.Builder
	sb.WriteString(prefix)
	sb.WriteString(strings.TrimSpace(strings.Join(args, " ")))
	sb.WriteString(suffix)
	sb.WriteString("\n")
	if version != "" {
		sb.WriteString(versionPrefix)
		sb.WriteString(version)
		sb.WriteString("\n")
	}
	sb.WriteString("\n")
	return sb.String()
}

// Parse reads the first two lines of a file. It reports false unless first
// is a muxt header line.
//
// An editor may have saved the file with a byte order mark, trailing
// whitespace or CRLF line endings; a header is recognized through those,
// so a hand-edited generated file is still cleaned up.
func Parse(first, second string) (Header, bool) {
	first = strings.TrimRight(strings.TrimPrefix(first, byteOrderMark), whitespace)
	second = strings.TrimRight(second, whitespace)
	if !strings.HasPrefix(first, prefix) || !strings.HasSuffix(first, suffix) {
		return Header{}, false
	}
	command := strings.TrimPrefix(first, prefix)
	command = strings.TrimSuffix(command, suffix)
	h := Header{Command: command}
	if version, ok := strings.CutPrefix(second, versionPrefix); ok {
		h.Version = version
	}
	return h, true
}

// Scan reads the Go files directly in dir and returns the headers of those
// generated by muxt, keyed by file path.
func Scan(dir string) (map[string]Header, error) {
	entries, err := os.ReadDir(dir)
	if err != nil {
		return nil, err
	}
	headers := make(map[string]Header)
	for _, entry := range entries {
		if entry.IsDir() || !strings.HasSuffix(entry.Name(), ".go") {
			continue
		}
		path := filepath.Join(dir, entry.Name())
		h, ok, err := Read(path)
		if err != nil {
			return nil, err
		}
		if ok {
			headers[path] = h
		}
	}
	return headers, nil
}

// Read parses the header of the file at path. It reports false for a file
// muxt did not generate, and an error only when the file cannot be read.
// Lines may be of any length and end in CRLF.
func Read(path string) (Header, bool, error) {
	f, err := os.Open(path)
	if err != nil {
		return Header{}, false, fmt.Errorf("failed to read %s: %w", path, err)
	}
	first, second, err := firstTwoLines(f)
	closeErr := f.Close()
	if err != nil {
		return Header{}, false, fmt.Errorf("failed to read %s: %w", path, err)
	}
	if closeErr != nil {
		return Header{}, false, fmt.Errorf("failed to read %s: %w", path, closeErr)
	}
	h, ok := Parse(first, second)
	return h, ok, nil
}

func firstTwoLines(r io.Reader) (first, second string, err error) {
	br := bufio.NewReader(r)
	first, err = readLine(br)
	if err != nil {
		return "", "", err
	}
	second, err = readLine(br)
	if err != nil {
		return "", "", err
	}
	return first, second, nil
}

func readLine(br *bufio.Reader) (string, error) {
	line, err := br.ReadString('\n')
	if err != nil && !errors.Is(err, io.EOF) {
		return "", err
	}
	return strings.TrimRight(line, "\r\n"), nil
}
