package header_test

import (
	"os"
	"path/filepath"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"

	"github.com/typelate/muxt/internal/header"
)

func TestFormat(t *testing.T) {
	for _, tt := range []struct {
		name    string
		args    []string
		version string
		want    string
	}{
		{name: "no arguments", want: "// Code generated by muxt generate . DO NOT EDIT.\n\n"},
		{name: "one argument", args: []string{"--output-htmx"}, want: "// Code generated by muxt generate --output-htmx. DO NOT EDIT.\n\n"},
		{name: "several arguments", args: []string{"--use-receiver-type=T", "--output-file=x.go"}, want: "// Code generated by muxt generate --use-receiver-type=T --output-file=x.go. DO NOT EDIT.\n\n"},
		{name: "with version", args: []string{"--output-htmx"}, version: "v1.2.3", want: "// Code generated by muxt generate --output-htmx. DO NOT EDIT.\n// muxt version: v1.2.3\n\n"},
		{name: "no arguments with version", version: "v1.2.3", want: "// Code generated by muxt generate . DO NOT EDIT.\n// muxt version: v1.2.3\n\n"},
	} {
		t.Run(tt.name, func(t *testing.T) {
			got := header.Format(tt.args, tt.version)
			assert.Equal(t, tt.want, got, "Format(%q, %q)", tt.args, tt.version)
		})
	}
}

func TestParse(t *testing.T) {
	for _, tt := range []struct {
		name          string
		first, second string
		want          header.Header
		wantOK        bool
	}{
		{name: "no arguments", first: "// Code generated by muxt generate . DO NOT EDIT.", want: header.Header{}, wantOK: true},
		{name: "arguments", first: "// Code generated by muxt generate --use-receiver-type=T --output-htmx. DO NOT EDIT.", want: header.Header{Command: "--use-receiver-type=T --output-htmx"}, wantOK: true},
		{name: "version", first: "// Code generated by muxt generate --output-htmx. DO NOT EDIT.", second: "// muxt version: v1.0.0", want: header.Header{Command: "--output-htmx", Version: "v1.0.0"}, wantOK: true},
		{name: "second line is not a version", first: "// Code generated by muxt generate --output-htmx. DO NOT EDIT.", second: "package server", want: header.Header{Command: "--output-htmx"}, wantOK: true},
		{name: "missing suffix", first: "// Code generated by muxt generate --output-htmx"},
		{name: "wrong prefix", first: "// Code generated by stringer. DO NOT EDIT."},
		{name: "prefix without trailing space", first: "// Code generated by muxt generate. DO NOT EDIT."},
		{name: "empty", first: ""},
	} {
		t.Run(tt.name, func(t *testing.T) {
			got, ok := header.Parse(tt.first, tt.second)
			assert.Equal(t, tt.wantOK, ok, "Parse(%q, %q) ok", tt.first, tt.second)
			assert.Equal(t, tt.want, got, "Parse(%q, %q)", tt.first, tt.second)
		})
	}
}

func TestHeaderArgs(t *testing.T) {
	for _, tt := range []struct {
		command string
		want    []string
	}{
		{command: "--x", want: []string{"--x"}},
		{command: "", want: []string{}},
		{command: "--a=b  --c", want: []string{"--a=b", "--c"}},
	} {
		t.Run(tt.command, func(t *testing.T) {
			got := header.Header{Command: tt.command}.Args()
			assert.Equal(t, tt.want, got, "Header{Command: %q}.Args()", tt.command)
		})
	}
}

func TestRoundTrip(t *testing.T) {
	for _, tt := range []struct {
		name    string
		args    []string
		version string
	}{
		{name: "empty"},
		{name: "one", args: []string{"--output-htmx"}},
		{name: "several", args: []string{"--use-receiver-type=T", "--output-routes-func=Routes"}},
		{name: "equals", args: []string{"--output-file=a=b.go"}, version: "v0.1.0"},
		{name: "version", args: []string{"--logger"}, version: "v0.20.0-dev.10"},
	} {
		t.Run(tt.name, func(t *testing.T) {
			text := header.Format(tt.args, tt.version)
			lines := splitLines(text)
			got, ok := header.Parse(lines[0], lines[1])
			require.True(t, ok, "Parse of Format(%q, %q) = %q", tt.args, tt.version, text)
			assert.Equal(t, tt.version, got.Version, "version of Format(%q, %q)", tt.args, tt.version)
			want := tt.args
			if want == nil {
				want = []string{}
			}
			assert.Equal(t, want, got.Args(), "args of Format(%q, %q)", tt.args, tt.version)
		})
	}
}

func splitLines(text string) [2]string {
	var lines [2]string
	var n int
	start := 0
	for i := 0; i < len(text) && n < len(lines); i++ {
		if text[i] == '\n' {
			lines[n] = text[start:i]
			n++
			start = i + 1
		}
	}
	return lines
}

func TestScan(t *testing.T) {
	dir := t.TempDir()
	for name, content := range map[string]string{
		"template_routes.go":  "// Code generated by muxt generate --use-receiver-type=T. DO NOT EDIT.\n// muxt version: v1.0.0\n\npackage server\n",
		"index_gen.go":        "// Code generated by muxt generate . DO NOT EDIT.\n",
		"no_newline.go":       "// Code generated by muxt generate --output-htmx. DO NOT EDIT.",
		"other_generated.go":  "// Code generated by stringer. DO NOT EDIT.\n",
		"handwritten.go":      "package server\n",
		"notes.txt":           "// Code generated by muxt generate --output-file=notes.txt. DO NOT EDIT.\n",
		"second_line.go":      "package server\n// Code generated by muxt generate --output-htmx. DO NOT EDIT.\n",
		"empty.go":            "",
		"sub/template_rou.go": "// Code generated by muxt generate --output-htmx. DO NOT EDIT.\n",
	} {
		path := filepath.Join(dir, filepath.FromSlash(name))
		require.NoError(t, os.MkdirAll(filepath.Dir(path), 0o755))
		require.NoError(t, os.WriteFile(path, []byte(content), 0o644))
	}

	files, err := header.Scan(dir)
	require.NoError(t, err)
	assert.Equal(t, map[string]header.Header{
		filepath.Join(dir, "template_routes.go"): {Command: "--use-receiver-type=T", Version: "v1.0.0"},
		filepath.Join(dir, "index_gen.go"):       {},
		filepath.Join(dir, "no_newline.go"):      {Command: "--output-htmx"},
	}, files, "only the .go files in the directory itself whose first line is the muxt header")

	_, err = header.Scan(filepath.Join(dir, "missing"))
	assert.Error(t, err)
}

func TestRead(t *testing.T) {
	dir := t.TempDir()
	for _, tt := range []struct {
		name, content string
		want          header.Header
		wantOK        bool
	}{
		{name: "lf.go", content: "// Code generated by muxt generate --output-htmx. DO NOT EDIT.\n// muxt version: v1.0.0\n\npackage a\n", want: header.Header{Command: "--output-htmx", Version: "v1.0.0"}, wantOK: true},
		{name: "crlf.go", content: "// Code generated by muxt generate --output-htmx. DO NOT EDIT.\r\n// muxt version: v1.0.0\r\n\r\npackage a\r\n", want: header.Header{Command: "--output-htmx", Version: "v1.0.0"}, wantOK: true},
		{name: "handwritten.go", content: "package a\n"},
		{name: "empty.go"},
	} {
		t.Run(tt.name, func(t *testing.T) {
			path := filepath.Join(dir, tt.name)
			require.NoError(t, os.WriteFile(path, []byte(tt.content), 0o644))
			got, ok, err := header.Read(path)
			require.NoError(t, err, "Read(%s)", tt.name)
			assert.Equal(t, tt.wantOK, ok, "Read(%s) ok", tt.name)
			assert.Equal(t, tt.want, got, "Read(%s)", tt.name)
		})
	}
	t.Run("missing", func(t *testing.T) {
		_, _, err := header.Read(filepath.Join(dir, "missing.go"))
		assert.Error(t, err, "Read(missing.go)")
	})
}
