// Code generated by counterfeiter. DO NOT EDIT.
package fake

import (
	"go/types"
	"sync"

	"github.com/typelate/muxt/internal/muxt"
)

type Checker struct {
	FileHeaderStub        func() (types.Type, error)
	fileHeaderMutex       sync.RWMutex
	fileHeaderArgsForCall []struct{}
	fileHeaderReturns     struct {
		result1 types.Type
		result2 error
	}
	fileHeaderReturnsOnCall map[int]struct {
		result1 types.Type
		result2 error
	}
	RawJSONStub        func() (types.Type, error)
	rawJSONMutex       sync.RWMutex
	rawJSONArgsForCall []struct{}
	rawJSONReturns     struct {
		result1 types.Type
		result2 error
	}
	rawJSONReturnsOnCall map[int]struct {
		result1 types.Type
		result2 error
	}
	ScopeTypeStub        func(string) (types.Type, error)
	scopeTypeMutex       sync.RWMutex
	scopeTypeArgsForCall []CheckerScopeTypeArgs
	scopeTypeReturns     struct {
		result1 types.Type
		result2 error
	}
	scopeTypeReturnsOnCall map[int]struct {
		result1 types.Type
		result2 error
	}
	TextMarshalerStub        func(types.Type) bool
	textMarshalerMutex       sync.RWMutex
	textMarshalerArgsForCall []CheckerTextMarshalerArgs
	textMarshalerReturns     struct {
		result1 bool
	}
	textMarshalerReturnsOnCall map[int]struct {
		result1 bool
	}
	TextUnmarshalerStub        func(types.Type) bool
	textUnmarshalerMutex       sync.RWMutex
	textUnmarshalerArgsForCall []CheckerTextUnmarshalerArgs
	textUnmarshalerReturns     struct {
		result1 bool
	}
	textUnmarshalerReturnsOnCall map[int]struct {
		result1 bool
	}
	invocations      map[string][][]interface{}
	callOrder        []string
	invocationsMutex sync.RWMutex
}

// CheckerScopeTypeArgs holds the arguments of one call to ScopeType.
type CheckerScopeTypeArgs struct {
	Arg1 string
}

// CheckerTextMarshalerArgs holds the arguments of one call to TextMarshaler.
type CheckerTextMarshalerArgs struct {
	Arg1 types.Type
}

// CheckerTextUnmarshalerArgs holds the arguments of one call to TextUnmarshaler.
type CheckerTextUnmarshalerArgs struct {
	Arg1 types.Type
}

func (fake *Checker) FileHeader() (types.Type, error) {
	fake.fileHeaderMutex.Lock()
	ret, specificReturn := fake.fileHeaderReturnsOnCall[len(fake.fileHeaderArgsForCall)]
	fake.fileHeaderArgsForCall = append(fake.fileHeaderArgsForCall, struct{}{})
	stub := fake.FileHeaderStub
	fakeReturns := fake.fileHeaderReturns
	fake.recordInvocation("FileHeader", []interface{}{})
	fake.fileHeaderMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *Checker) FileHeaderCallCount() int {
	fake.fileHeaderMutex.RLock()
	defer fake.fileHeaderMutex.RUnlock()
	return len(fake.fileHeaderArgsForCall)
}

func (fake *Checker) FileHeaderCalls(stub func() (types.Type, error)) {
	fake.fileHeaderMutex.Lock()
	defer fake.fileHeaderMutex.Unlock()
	fake.FileHeaderStub = stub
}

func (fake *Checker) FileHeaderReturns(result1 types.Type, result2 error) {
	fake.fileHeaderMutex.Lock()
	defer fake.fileHeaderMutex.Unlock()
	fake.FileHeaderStub = nil
	fake.fileHeaderReturns = struct {
		result1 types.Type
		result2 error
	}{result1, result2}
}

func (fake *Checker) FileHeaderReturnsOnCall(i int, result1 types.Type, result2 error) {
	fake.fileHeaderMutex.Lock()
	defer fake.fileHeaderMutex.Unlock()
	fake.FileHeaderStub = nil
	if fake.fileHeaderReturnsOnCall == nil {
		fake.fileHeaderReturnsOnCall = make(map[int]struct {
			result1 types.Type
			result2 error
		})
	}
	fake.fileHeaderReturnsOnCall[i] = struct {
		result1 types.Type
		result2 error
	}{result1, result2}
}

func (fake *Checker) RawJSON() (types.Type, error) {
	fake.rawJSONMutex.Lock()
	ret, specificReturn := fake.rawJSONReturnsOnCall[len(fake.rawJSONArgsForCall)]
	fake.rawJSONArgsForCall = append(fake.rawJSONArgsForCall, struct{}{})
	stub := fake.RawJSONStub
	fakeReturns := fake.rawJSONReturns
	fake.recordInvocation("RawJSON", []interface{}{})
	fake.rawJSONMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *Checker) RawJSONCallCount() int {
	fake.rawJSONMutex.RLock()
	defer fake.rawJSONMutex.RUnlock()
	return len(fake.rawJSONArgsForCall)
}

func (fake *Checker) RawJSONCalls(stub func() (types.Type, error)) {
	fake.rawJSONMutex.Lock()
	defer fake.rawJSONMutex.Unlock()
	fake.RawJSONStub = stub
}

func (fake *Checker) RawJSONReturns(result1 types.Type, result2 error) {
	fake.rawJSONMutex.Lock()
	defer fake.rawJSONMutex.Unlock()
	fake.RawJSONStub = nil
	fake.rawJSONReturns = struct {
		result1 types.Type
		result2 error
	}{result1, result2}
}

func (fake *Checker) RawJSONReturnsOnCall(i int, result1 types.Type, result2 error) {
	fake.rawJSONMutex.Lock()
	defer fake.rawJSONMutex.Unlock()
	fake.RawJSONStub = nil
	if fake.rawJSONReturnsOnCall == nil {
		fake.rawJSONReturnsOnCall = make(map[int]struct {
			result1 types.Type
			result2 error
		})
	}
	fake.rawJSONReturnsOnCall[i] = struct {
		result1 types.Type
		result2 error
	}{result1, result2}
}

func (fake *Checker) ScopeType(arg1 string) (types.Type, error) {
	fake.scopeTypeMutex.Lock()
	ret, specificReturn := fake.scopeTypeReturnsOnCall[len(fake.scopeTypeArgsForCall)]
	fake.scopeTypeArgsForCall = append(fake.scopeTypeArgsForCall, CheckerScopeTypeArgs{arg1})
	stub := fake.ScopeTypeStub
	fakeReturns := fake.scopeTypeReturns
	fake.recordInvocation("ScopeType", []interface{}{arg1})
	fake.scopeTypeMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *Checker) ScopeTypeCallCount() int {
	fake.scopeTypeMutex.RLock()
	defer fake.scopeTypeMutex.RUnlock()
	return len(fake.scopeTypeArgsForCall)
}

func (fake *Checker) ScopeTypeCalls(stub func(string) (types.Type, error)) {
	fake.scopeTypeMutex.Lock()
	defer fake.scopeTypeMutex.Unlock()
	fake.ScopeTypeStub = stub
}

func (fake *Checker) ScopeTypeArgsForCall(i int) string {
	fake.scopeTypeMutex.RLock()
	defer fake.scopeTypeMutex.RUnlock()
	argsForCall := fake.scopeTypeArgsForCall[i]
	return argsForCall.Arg1
}

func (fake *Checker) ScopeTypeArgs() []CheckerScopeTypeArgs {
	fake.scopeTypeMutex.RLock()
	defer fake.scopeTypeMutex.RUnlock()
	args := make([]CheckerScopeTypeArgs, len(fake.scopeTypeArgsForCall))
	copy(args, fake.scopeTypeArgsForCall)
	return args
}

func (fake *Checker) ScopeTypeReturns(result1 types.Type, result2 error) {
	fake.scopeTypeMutex.Lock()
	defer fake.scopeTypeMutex.Unlock()
	fake.ScopeTypeStub = nil
	fake.scopeTypeReturns = struct {
		result1 types.Type
		result2 error
	}{result1, result2}
}

func (fake *Checker) ScopeTypeReturnsOnCall(i int, result1 types.Type, result2 error) {
	fake.scopeTypeMutex.Lock()
	defer fake.scopeTypeMutex.Unlock()
	fake.ScopeTypeStub = nil
	if fake.scopeTypeReturnsOnCall == nil {
		fake.scopeTypeReturnsOnCall = make(map[int]struct {
			result1 types.Type
			result2 error
		})
	}
	fake.scopeTypeReturnsOnCall[i] = struct {
		result1 types.Type
		result2 error
	}{result1, result2}
}

func (fake *Checker) TextMarshaler(arg1 types.Type) bool {
	fake.textMarshalerMutex.Lock()
	ret, specificReturn := fake.textMarshalerReturnsOnCall[len(fake.textMarshalerArgsForCall)]
	fake.textMarshalerArgsForCall = append(fake.textMarshalerArgsForCall, CheckerTextMarshalerArgs{arg1})
	stub := fake.TextMarshalerStub
	fakeReturns := fake.textMarshalerReturns
	fake.recordInvocation("TextMarshaler", []interface{}{arg1})
	fake.textMarshalerMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *Checker) TextMarshalerCallCount() int {
	fake.textMarshalerMutex.RLock()
	defer fake.textMarshalerMutex.RUnlock()
	return len(fake.textMarshalerArgsForCall)
}

func (fake *Checker) TextMarshalerCalls(stub func(types.Type) bool) {
	fake.textMarshalerMutex.Lock()
	defer fake.textMarshalerMutex.Unlock()
	fake.TextMarshalerStub = stub
}

func (fake *Checker) TextMarshalerArgsForCall(i int) types.Type {
	fake.textMarshalerMutex.RLock()
	defer fake.textMarshalerMutex.RUnlock()
	argsForCall := fake.textMarshalerArgsForCall[i]
	return argsForCall.Arg1
}

func (fake *Checker) TextMarshalerArgs() []CheckerTextMarshalerArgs {
	fake.textMarshalerMutex.RLock()
	defer fake.textMarshalerMutex.RUnlock()
	args := make([]CheckerTextMarshalerArgs, len(fake.textMarshalerArgsForCall))
	copy(args, fake.textMarshalerArgsForCall)
	return args
}

func (fake *Checker) TextMarshalerReturns(result1 bool) {
	fake.textMarshalerMutex.Lock()
	defer fake.textMarshalerMutex.Unlock()
	fake.TextMarshalerStub = nil
	fake.textMarshalerReturns = struct {
		result1 bool
	}{result1}
}

func (fake *Checker) TextMarshalerReturnsOnCall(i int, result1 bool) {
	fake.textMarshalerMutex.Lock()
	defer fake.textMarshalerMutex.Unlock()
	fake.TextMarshalerStub = nil
	if fake.textMarshalerReturnsOnCall == nil {
		fake.textMarshalerReturnsOnCall = make(map[int]struct {
			result1 bool
		})
	}
	fake.textMarshalerReturnsOnCall[i] = struct {
		result1 bool
	}{result1}
}

func (fake *Checker) TextUnmarshaler(arg1 types.Type) bool {
	fake.textUnmarshalerMutex.Lock()
	ret, specificReturn := fake.textUnmarshalerReturnsOnCall[len(fake.textUnmarshalerArgsForCall)]
	fake.textUnmarshalerArgsForCall = append(fake.textUnmarshalerArgsForCall, CheckerTextUnmarshalerArgs{arg1})
	stub := fake.TextUnmarshalerStub
	fakeReturns := fake.textUnmarshalerReturns
	fake.recordInvocation("TextUnmarshaler", []interface{}{arg1})
	fake.textUnmarshalerMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *Checker) TextUnmarshalerCallCount() int {
	fake.textUnmarshalerMutex.RLock()
	defer fake.textUnmarshalerMutex.RUnlock()
	return len(fake.textUnmarshalerArgsForCall)
}

func (fake *Checker) TextUnmarshalerCalls(stub func(types.Type) bool) {
	fake.textUnmarshalerMutex.Lock()
	defer fake.textUnmarshalerMutex.Unlock()
	fake.TextUnmarshalerStub = stub
}

func (fake *Checker) TextUnmarshalerArgsForCall(i int) types.Type {
	fake.textUnmarshalerMutex.RLock()
	defer fake.textUnmarshalerMutex.RUnlock()
	argsForCall := fake.textUnmarshalerArgsForCall[i]
	return argsForCall.Arg1
}

func (fake *Checker) TextUnmarshalerArgs() []CheckerTextUnmarshalerArgs {
	fake.textUnmarshalerMutex.RLock()
	defer fake.textUnmarshalerMutex.RUnlock()
	args := make([]CheckerTextUnmarshalerArgs, len(fake.textUnmarshalerArgsForCall))
	copy(args, fake.textUnmarshalerArgsForCall)
	return args
}

func (fake *Checker) TextUnmarshalerReturns(result1 bool) {
	fake.textUnmarshalerMutex.Lock()
	defer fake.textUnmarshalerMutex.Unlock()
	fake.TextUnmarshalerStub = nil
	fake.textUnmarshalerReturns = struct {
		result1 bool
	}{result1}
}

func (fake *Checker) TextUnmarshalerReturnsOnCall(i int, result1 bool) {
	fake.textUnmarshalerMutex.Lock()
	defer fake.textUnmarshalerMutex.Unlock()
	fake.TextUnmarshalerStub = nil
	if fake.textUnmarshalerReturnsOnCall == nil {
		fake.textUnmarshalerReturnsOnCall = make(map[int]struct {
			result1 bool
		})
	}
	fake.textUnmarshalerReturnsOnCall[i] = struct {
		result1 bool
	}{result1}
}

func (fake *Checker) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *Checker) CallOrder() []string {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	order := make([]string, len(fake.callOrder))
	copy(order, fake.callOrder)
	return order
}

func (fake *Checker) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	fake.callOrder = append(fake.callOrder, key)
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ muxt.Checker = new(Checker)
