// Code generated by muxt generate --use-receiver-type=Server. DO NOT EDIT.
// muxt version: (devel)

package main

import (
	"bytes"
	"cmp"
	"errors"
	"fmt"
	"log/slog"
	"net/http"
	"path"
	"strconv"
)

type RoutesReceiver interface {
	Count() int64
	Decrement() int64
	Increment() int64
}

func TemplateRoutes(mux *http.ServeMux, receiver RoutesReceiver) TemplateRoutePaths {
	pathsPrefix := ""
	mux.HandleFunc("/", func(response http.ResponseWriter, request *http.Request) {
		var td = TemplateData[RoutesReceiver, int64]{receiver: receiver, response: response, request: request, pathsPrefix: pathsPrefix}
		if len(td.errList) == 0 {
			td.result = receiver.Count()
			td.okay = true
		}
		buf := bytes.NewBuffer(nil)
		if err := templates.ExecuteTemplate(buf, "/ Count()", &td); err != nil {
			slog.ErrorContext(request.Context(), "failed to render page", slog.String("path", request.URL.Path), slog.String("pattern", request.Pattern), slog.String("error", err.Error()))
			http.Error(response, "failed to render page", http.StatusInternalServerError)
			return
		}
		statusCode := cmp.Or(td.statusCode, td.errStatusCode, http.StatusOK)
		if contentType := response.Header().Get("content-type"); contentType == "" {
			response.Header().Set("content-type", "text/html; charset=utf-8")
		}
		response.Header().Set("content-length", strconv.Itoa(buf.Len()))
		response.WriteHeader(statusCode)
		_, _ = buf.WriteTo(response)
	})
	mux.HandleFunc("POST /count", func(response http.ResponseWriter, request *http.Request) {
		var td = TemplateData[RoutesReceiver, struct {
		}]{receiver: receiver, response: response, request: request, pathsPrefix: pathsPrefix}
		buf := bytes.NewBuffer(nil)
		if err := templates.ExecuteTemplate(buf, "POST /count", &td); err != nil {
			slog.ErrorContext(request.Context(), "failed to render page", slog.String("path", request.URL.Path), slog.String("pattern", request.Pattern), slog.String("error", err.Error()))
			http.Error(response, "failed to render page", http.StatusInternalServerError)
			return
		}
		statusCode := cmp.Or(td.statusCode, td.errStatusCode, http.StatusOK)
		if td.redirectURL != "" {
			http.Redirect(response, request, td.redirectURL, statusCode)
			return
		}
		if contentType := response.Header().Get("content-type"); contentType == "" {
			response.Header().Set("content-type", "text/html; charset=utf-8")
		}
		response.Header().Set("content-length", strconv.Itoa(buf.Len()))
		response.WriteHeader(statusCode)
		_, _ = buf.WriteTo(response)
	})
	mux.HandleFunc("/decrement-count", func(response http.ResponseWriter, request *http.Request) {
		var td = TemplateData[RoutesReceiver, int64]{receiver: receiver, response: response, request: request, pathsPrefix: pathsPrefix}
		if len(td.errList) == 0 {
			td.result = receiver.Decrement()
			td.okay = true
		}
		buf := bytes.NewBuffer(nil)
		if err := templates.ExecuteTemplate(buf, "/decrement-count Decrement()", &td); err != nil {
			slog.ErrorContext(request.Context(), "failed to render page", slog.String("path", request.URL.Path), slog.String("pattern", request.Pattern), slog.String("error", err.Error()))
			http.Error(response, "failed to render page", http.StatusInternalServerError)
			return
		}
		statusCode := cmp.Or(td.statusCode, td.errStatusCode, http.StatusOK)
		if td.redirectURL != "" {
			http.Redirect(response, request, td.redirectURL, statusCode)
			return
		}
		if contentType := response.Header().Get("content-type"); contentType == "" {
			response.Header().Set("content-type", "text/html; charset=utf-8")
		}
		response.Header().Set("content-length", strconv.Itoa(buf.Len()))
		response.WriteHeader(statusCode)
		_, _ = buf.WriteTo(response)
	})
	mux.HandleFunc("/increment-count", func(response http.ResponseWriter, request *http.Request) {
		var td = TemplateData[RoutesReceiver, int64]{receiver: receiver, response: response, request: request, pathsPrefix: pathsPrefix}
		if len(td.errList) == 0 {
			td.result = receiver.Increment()
			td.okay = true
		}
		buf := bytes.NewBuffer(nil)
		if err := templates.ExecuteTemplate(buf, "/increment-count Increment()", &td); err != nil {
			slog.ErrorContext(request.Context(), "failed to render page", slog.String("path", request.URL.Path), slog.String("pattern", request.Pattern), slog.String("error", err.Error()))
			http.Error(response, "failed to render page", http.StatusInternalServerError)
			return
		}
		statusCode := cmp.Or(td.statusCode, td.errStatusCode, http.StatusOK)
		if td.redirectURL != "" {
			http.Redirect(response, request, td.redirectURL, statusCode)
			return
		}
		if contentType := response.Header().Get("content-type"); contentType == "" {
			response.Header().Set("content-type", "text/html; charset=utf-8")
		}
		response.Header().Set("content-length", strconv.Itoa(buf.Len()))
		response.WriteHeader(statusCode)
		_, _ = buf.WriteTo(response)
	})
	return TemplateRoutePaths{pathsPrefix: pathsPrefix}
}

type TemplateData[R any, T any] struct {
	receiver      R
	response      http.ResponseWriter
	request       *http.Request
	result        T
	statusCode    int
	errStatusCode int
	okay          bool
	errList       []error
	redirectURL   string
	pathsPrefix   string
}

func (data *TemplateData[R, T]) MuxtVersion() string {
	const muxtVersion = "(devel)"
	return muxtVersion
}

func (data *TemplateData[R, T]) Path() TemplateRoutePaths {
	return TemplateRoutePaths{pathsPrefix: data.pathsPrefix}
}

func (data *TemplateData[R, T]) Result() T {
	return data.result
}

func (data *TemplateData[R, T]) Request() *http.Request {
	return data.request
}

func (data *TemplateData[R, T]) StatusCode(statusCode int) *TemplateData[R, T] {
	data.statusCode = statusCode
	return data
}

func (data *TemplateData[R, T]) Header(key, value string) *TemplateData[R, T] {
	data.response.Header().Set(key, value)
	return data
}

func (data *TemplateData[R, T]) Ok() bool {
	return data.okay
}

func (data *TemplateData[R, T]) Err() error {
	return errors.Join(data.errList...)
}

func (data *TemplateData[R, T]) Receiver() R {
	return data.receiver
}

func (data *TemplateData[R, T]) Redirect(url string, code int) (*TemplateData[R, T], error) {
	if code < 300 || code >= 400 {
		return data, fmt.Errorf("invalid status code %d for redirect", code)
	}
	data.redirectURL = url
	return data.StatusCode(code), nil
}

type TemplateRoutePaths struct {
	pathsPrefix string
}

func (routePaths TemplateRoutePaths) Count() string {
	return "/"
}

func (routePaths TemplateRoutePaths) CreateCount() string {
	return path.Join(cmp.Or(routePaths.pathsPrefix, "/"), "count")
}

func (routePaths TemplateRoutePaths) Decrement() string {
	return path.Join(cmp.Or(routePaths.pathsPrefix, "/"), "decrement-count")
}

func (routePaths TemplateRoutePaths) Increment() string {
	return path.Join(cmp.Or(routePaths.pathsPrefix, "/"), "increment-count")
}
