// Code generated by muxt generate --use-receiver-type=Backend --use-receiver-type-package=github.com/typelate/muxt/docs/examples/simple. DO NOT EDIT.
// muxt version: (devel)

package main

import (
	"bytes"
	"cmp"
	"context"
	"errors"
	"fmt"
	"log/slog"
	"net/http"
	"path"
	"strconv"
	"sync"
)

type RoutesReceiver interface {
	SubmitFormEditRow(fruitID int, form EditRow) (Row, error)
	GetFormEditRow(fruitID int) (Row, error)
	List(_ context.Context) []Row
}

func TemplateRoutes(mux *http.ServeMux, receiver RoutesReceiver) TemplateRoutePaths {
	pathsPrefix := ""
	bytesBufferPool := sync.Pool{New: func() any {
		return bytes.NewBuffer(nil)
	}}
	mux.HandleFunc("PATCH /fruits/{id}", func(response http.ResponseWriter, request *http.Request) {
		var td = TemplateData[RoutesReceiver, Row]{receiver: receiver, response: response, request: request, pathsPrefix: pathsPrefix}
		idParsed, err := strconv.Atoi(request.PathValue("id"))
		if err != nil {
			td.errList = append(td.errList, err)
			td.errStatusCode = http.StatusBadRequest
		}
		idPathParam := idParsed
		if err := request.ParseForm(); err != nil {
			http.Error(response, err.Error(), http.StatusBadRequest)
			return
		}
		var form EditRow
		{
			value, err := strconv.Atoi(request.FormValue("count"))
			if err != nil {
				td.errList = append(td.errList, err)
				td.errStatusCode = http.StatusBadRequest
			} else {
				if value < 0 {
					td.errList = append(td.errList, errors.New("count must not be less than 0"))
					td.errStatusCode = http.StatusBadRequest
				}
			}
			form.Value = value
		}
		buf := bytesBufferPool.Get().(*bytes.Buffer)
		buf.Reset()
		defer bytesBufferPool.Put(buf)
		if len(td.errList) == 0 {
			var err error
			td.result, err = receiver.SubmitFormEditRow(idPathParam, form)
			if err != nil {
				td.errList = append(td.errList, err)
				td.errStatusCode = http.StatusInternalServerError
			}
		}
		if err := templates.ExecuteTemplate(buf, "PATCH /fruits/{id} SubmitFormEditRow(id, form)", &td); err != nil {
			slog.ErrorContext(request.Context(), "failed to render page", slog.String("path", request.URL.Path), slog.String("pattern", request.Pattern), slog.String("error", err.Error()))
			http.Error(response, "failed to render page", http.StatusInternalServerError)
			return
		}
		defaultStatusCode := http.StatusOK
		if buf.Len() == 0 {
			defaultStatusCode = http.StatusNoContent
		}
		statusCode := cmp.Or(td.statusCode, td.errStatusCode, defaultStatusCode)
		if td.redirectURL != "" {
			http.Redirect(response, request, td.redirectURL, statusCode)
			return
		}
		if contentType := response.Header().Get("content-type"); contentType == "" {
			response.Header().Set("content-type", "text/html; charset=utf-8")
		}
		response.Header().Set("content-length", strconv.Itoa(buf.Len()))
		response.WriteHeader(statusCode)
		_, _ = buf.WriteTo(response)
	})
	mux.HandleFunc("GET /fruits/{id}/edit", func(response http.ResponseWriter, request *http.Request) {
		var td = TemplateData[RoutesReceiver, Row]{receiver: receiver, response: response, request: request, pathsPrefix: pathsPrefix}
		idParsed, err := strconv.Atoi(request.PathValue("id"))
		if err != nil {
			td.errList = append(td.errList, err)
			td.errStatusCode = http.StatusBadRequest
		}
		idPathParam := idParsed
		buf := bytesBufferPool.Get().(*bytes.Buffer)
		buf.Reset()
		defer bytesBufferPool.Put(buf)
		if len(td.errList) == 0 {
			var err error
			td.result, err = receiver.GetFormEditRow(idPathParam)
			if err != nil {
				td.errList = append(td.errList, err)
				td.errStatusCode = http.StatusInternalServerError
			}
		}
		if err := templates.ExecuteTemplate(buf, "GET /fruits/{id}/edit GetFormEditRow(id)", &td); err != nil {
			slog.ErrorContext(request.Context(), "failed to render page", slog.String("path", request.URL.Path), slog.String("pattern", request.Pattern), slog.String("error", err.Error()))
			http.Error(response, "failed to render page", http.StatusInternalServerError)
			return
		}
		defaultStatusCode := http.StatusOK
		if buf.Len() == 0 {
			defaultStatusCode = http.StatusNoContent
		}
		statusCode := cmp.Or(td.statusCode, td.errStatusCode, defaultStatusCode)
		if td.redirectURL != "" {
			http.Redirect(response, request, td.redirectURL, statusCode)
			return
		}
		if contentType := response.Header().Get("content-type"); contentType == "" {
			response.Header().Set("content-type", "text/html; charset=utf-8")
		}
		response.Header().Set("content-length", strconv.Itoa(buf.Len()))
		response.WriteHeader(statusCode)
		_, _ = buf.WriteTo(response)
	})
	mux.HandleFunc("GET /help", func(response http.ResponseWriter, request *http.Request) {
		var td = TemplateData[RoutesReceiver, struct {
		}]{receiver: receiver, response: response, request: request, pathsPrefix: pathsPrefix}
		buf := bytesBufferPool.Get().(*bytes.Buffer)
		buf.Reset()
		defer bytesBufferPool.Put(buf)
		if err := templates.ExecuteTemplate(buf, "GET /help", &td); err != nil {
			slog.ErrorContext(request.Context(), "failed to render page", slog.String("path", request.URL.Path), slog.String("pattern", request.Pattern), slog.String("error", err.Error()))
			http.Error(response, "failed to render page", http.StatusInternalServerError)
			return
		}
		defaultStatusCode := http.StatusOK
		if buf.Len() == 0 {
			defaultStatusCode = http.StatusNoContent
		}
		statusCode := cmp.Or(td.statusCode, td.errStatusCode, defaultStatusCode)
		if contentType := response.Header().Get("content-type"); contentType == "" {
			response.Header().Set("content-type", "text/html; charset=utf-8")
		}
		response.Header().Set("content-length", strconv.Itoa(buf.Len()))
		response.WriteHeader(statusCode)
		_, _ = buf.WriteTo(response)
	})
	mux.HandleFunc("GET /{$}", func(response http.ResponseWriter, request *http.Request) {
		var td = TemplateData[RoutesReceiver, []Row]{receiver: receiver, response: response, request: request, pathsPrefix: pathsPrefix}
		ctx := request.Context()
		buf := bytesBufferPool.Get().(*bytes.Buffer)
		buf.Reset()
		defer bytesBufferPool.Put(buf)
		if len(td.errList) == 0 {
			td.result = receiver.List(ctx)
			td.okay = true
		}
		if err := templates.ExecuteTemplate(buf, "GET /{$} List(ctx)", &td); err != nil {
			slog.ErrorContext(request.Context(), "failed to render page", slog.String("path", request.URL.Path), slog.String("pattern", request.Pattern), slog.String("error", err.Error()))
			http.Error(response, "failed to render page", http.StatusInternalServerError)
			return
		}
		defaultStatusCode := http.StatusOK
		if buf.Len() == 0 {
			defaultStatusCode = http.StatusNoContent
		}
		statusCode := cmp.Or(td.statusCode, td.errStatusCode, defaultStatusCode)
		if td.redirectURL != "" {
			http.Redirect(response, request, td.redirectURL, statusCode)
			return
		}
		if contentType := response.Header().Get("content-type"); contentType == "" {
			response.Header().Set("content-type", "text/html; charset=utf-8")
		}
		response.Header().Set("content-length", strconv.Itoa(buf.Len()))
		response.WriteHeader(statusCode)
		_, _ = buf.WriteTo(response)
	})
	return TemplateRoutePaths{routes: TemplateRouteBuilder{pathsPrefix: pathsPrefix}}
}

type TemplateData[R any, T any] struct {
	receiver      R
	response      http.ResponseWriter
	request       *http.Request
	result        T
	statusCode    int
	errStatusCode int
	okay          bool
	errList       []error
	redirectURL   string
	pathsPrefix   string
}

func (data *TemplateData[R, T]) MuxtVersion() string {
	const muxtVersion = "(devel)"
	return muxtVersion
}

func (data *TemplateData[R, T]) Path() TemplateRoutePaths {
	return TemplateRoutePaths{routes: TemplateRouteBuilder{pathsPrefix: data.pathsPrefix}}
}

func (data *TemplateData[R, T]) Route() TemplateRouteBuilder {
	return TemplateRouteBuilder{pathsPrefix: data.pathsPrefix}
}

func (data *TemplateData[R, T]) Result() T {
	return data.result
}

func (data *TemplateData[R, T]) Request() *http.Request {
	return data.request
}

func (data *TemplateData[R, T]) StatusCode(statusCode int) *TemplateData[R, T] {
	data.statusCode = statusCode
	return data
}

func (data *TemplateData[R, T]) Header(key, value string) *TemplateData[R, T] {
	data.response.Header().Set(key, value)
	return data
}

func (data *TemplateData[R, T]) Ok() bool {
	return data.okay
}

func (data *TemplateData[R, T]) Err() error {
	return errors.Join(data.errList...)
}

func (data *TemplateData[R, T]) Receiver() R {
	return data.receiver
}

func (data *TemplateData[R, T]) Redirect(url string, code int) (*TemplateData[R, T], error) {
	if code < 300 || code >= 400 {
		return data, fmt.Errorf("invalid status code %d for redirect", code)
	}
	data.redirectURL = url
	return data.StatusCode(code), nil
}

func (data *TemplateData[R, T]) RedirectMultipleChoices(url string) (*TemplateData[R, T], error) {
	return data.Redirect(url, http.StatusMultipleChoices)
}

func (data *TemplateData[R, T]) RedirectMovedPermanently(url string) (*TemplateData[R, T], error) {
	return data.Redirect(url, http.StatusMovedPermanently)
}

func (data *TemplateData[R, T]) RedirectFound(url string) (*TemplateData[R, T], error) {
	return data.Redirect(url, http.StatusFound)
}

func (data *TemplateData[R, T]) RedirectSeeOther(url string) (*TemplateData[R, T], error) {
	return data.Redirect(url, http.StatusSeeOther)
}

func (data *TemplateData[R, T]) String() string {
	return ""
}

type TemplateRoutePaths struct {
	routes TemplateRouteBuilder
}
type TemplateRouteBuilder struct {
	pathsPrefix string
}
type TemplateRoute struct {
	method string
	path   string
}

func (route TemplateRoute) Path() string {
	return route.path
}

func (route TemplateRoute) String() string {
	return route.Path()
}

func (route TemplateRoute) Method() string {
	return route.method
}

func (routes TemplateRouteBuilder) SubmitFormEditRow(idPathParam int) TemplateRoute {
	return TemplateRoute{method: http.MethodPatch, path: path.Join(cmp.Or(routes.pathsPrefix, "/"), "fruits", strconv.Itoa(idPathParam))}
}

func (routePaths TemplateRoutePaths) SubmitFormEditRow(idPathParam int) string {
	return routePaths.routes.SubmitFormEditRow(idPathParam).Path()
}

func (routes TemplateRouteBuilder) GetFormEditRow(idPathParam int) TemplateRoute {
	return TemplateRoute{method: http.MethodGet, path: path.Join(cmp.Or(routes.pathsPrefix, "/"), "fruits", strconv.Itoa(idPathParam), "edit")}
}

func (routePaths TemplateRoutePaths) GetFormEditRow(idPathParam int) string {
	return routePaths.routes.GetFormEditRow(idPathParam).Path()
}

func (routes TemplateRouteBuilder) ReadHelp() TemplateRoute {
	return TemplateRoute{method: http.MethodGet, path: path.Join(cmp.Or(routes.pathsPrefix, "/"), "help")}
}

func (routePaths TemplateRoutePaths) ReadHelp() string {
	return routePaths.routes.ReadHelp().Path()
}

func (routes TemplateRouteBuilder) List() TemplateRoute {
	return TemplateRoute{method: http.MethodGet, path: "/"}
}

func (routePaths TemplateRoutePaths) List() string {
	return routePaths.routes.List().Path()
}
