package cli

import (
	"errors"
	"fmt"
	"io"
	"log"
	"os"
	"path/filepath"

	"github.com/spf13/pflag"

	"github.com/typelate/muxt/internal/generate"
	"github.com/typelate/muxt/internal/header"
)

// ownedGeneratedFiles returns the muxt-generated files in dir that a run
// with routesFunction may delete.
//
// CLEANUP HEURISTIC:
// We automatically delete muxt-generated files that are no longer needed to avoid
// manual cleanup when template files are renamed or generation modes change.
//
// Files are identified by:
//  1. Presence of "// Code generated by muxt generate" comment
//  2. The --output-routes-func recorded in its header equals the current one
//     (to differentiate multiple route sets)
//
// Cleanup scenarios:
//   - Template renamed: old_template_routes_gen.go deleted when template renamed to new.gohtml
//   - Switch to single-file: all per-file *_template_routes_gen.go files deleted
//   - Switch to multi-file: old single template_routes.go overwritten (if same filename)
//   - Routes function unchanged: only deletes files matching current routes function
//
// IMPORTANT: If you change --output-routes-func value, old files with the previous
// routes function name will NOT be deleted (to allow multiple route sets to coexist).
// To clean up after changing routes function name, manually delete old files or
// temporarily use the old --output-routes-func value with current templates.
func ownedGeneratedFiles(dir, routesFunction string) (map[string]bool, error) {
	generated, err := header.Scan(dir)
	if err != nil {
		return nil, err
	}
	owned := make(map[string]bool, len(generated))
	for path, h := range generated {
		var (
			config     generate.RoutesFileConfiguration
			deprecated string
		)
		set := pflag.NewFlagSet("parse-old", pflag.ContinueOnError)
		addGenerateFlags(set, &config, &deprecated)
		set.SetOutput(io.Discard)
		if err := set.Parse(h.Args()); err != nil {
			log.Printf("WARNING: ignored generated file %s because arguments failed to parse: %s", path, err)
			owned[path] = true
			continue
		}
		if config.RoutesFunction == routesFunction {
			owned[path] = true
		}
	}
	return owned, nil
}

// writeGeneratedFiles writes files, each after the header that records
// config, and removes the ones already written if a write fails. It returns
// the paths written.
func writeGeneratedFiles(stdout io.Writer, files []generate.GeneratedFile, config generate.RoutesFileConfiguration) (map[string]bool, error) {
	written := make(map[string]bool, len(files))
	for i, file := range files {
		content := header.Format(configToArgs(config), config.MuxtVersion) + file.Content
		if err := os.WriteFile(file.Path, []byte(content), 0o644); err != nil {
			for _, f := range files[:i] {
				if rmErr := os.Remove(f.Path); rmErr != nil {
					err = errors.Join(err, rmErr)
				}
			}
			return nil, err
		}
		_, _ = fmt.Fprintf(stdout, "wrote %s: %s\n", filepath.Base(file.Path), plural(file.Routes, "route"))
		written[file.Path] = true
	}
	return written, nil
}

// removeOrphans deletes the owned files a run did not write again.
func removeOrphans(owned, written map[string]bool) error {
	for path := range owned {
		if written[path] {
			continue
		}
		if err := os.Remove(path); err != nil && !os.IsNotExist(err) {
			return fmt.Errorf("failed to remove orphaned file %s: %w", path, err)
		}
	}
	return nil
}

func plural(n int, noun string) string {
	if n == 1 {
		return "1 " + noun
	}
	return fmt.Sprintf("%d %ss", n, noun)
}
