package cli

import (
	"bytes"
	"errors"
	"fmt"
	"io"
	"log"
	"os"
	"path/filepath"

	"github.com/spf13/cobra"
	"github.com/spf13/pflag"

	"github.com/typelate/muxt/internal/analysis"
	"github.com/typelate/muxt/internal/generate"
	"github.com/typelate/muxt/internal/load"
	"github.com/typelate/muxt/internal/mutation"
)

// This file holds what each command does with its configuration: load the
// package, run the implementation, and write what it produced. Everything
// the flags decide happens before a runner is called, in commands.go.

func runRoutes(cmd *cobra.Command, wd string, config analysis.DefinitionsConfiguration) error {
	_, pl, err := load.Packages(wd, config.ReceiverPackage)
	if err != nil {
		return err
	}
	pkg, receiver, err := load.RoutesSource(wd, pl, config)
	if err != nil {
		printMultiLineError(cmd, err)
		return err
	}
	results, err := analysis.NewRoutes(pkg, receiver)
	if err != nil {
		printMultiLineError(cmd, err)
		return err
	}
	for _, result := range results {
		if err := writeResult(cmd, cmd.OutOrStdout(), result); err != nil {
			return err
		}
	}
	return nil
}

func runCheck(cmd *cobra.Command, wd string, config analysis.CheckConfiguration) error {
	_, pl, err := load.Packages(wd)
	if err != nil {
		return err
	}
	logger := log.New(cmd.ErrOrStderr(), "", 0)
	warnPartialAST(logger, pl)
	checked, err := func() (int, error) {
		pkg, err := load.Package(wd, pl, config.TemplatesVariables)
		if err != nil {
			return 0, err
		}
		return analysis.Check(config, logger, pkg)
	}()
	if err != nil {
		if printMultiLineError(cmd, err) {
			return err
		}
		return fmt.Errorf("fail: %s", err)
	}
	if checked == 1 {
		_, _ = fmt.Fprintln(cmd.OutOrStdout(), "ok: 1 template")
	} else {
		_, _ = fmt.Fprintf(cmd.OutOrStdout(), "ok: %d templates\n", checked)
	}
	return nil
}

func runTemplateCallers(cmd *cobra.Command, wd string, config analysis.TemplateCallersConfiguration) error {
	_, pl, err := load.Packages(wd)
	if err != nil {
		return err
	}
	pkg, err := load.Package(wd, pl, config.TemplatesVariables)
	if err != nil {
		return err
	}
	result, err := analysis.NewTemplateCallers(config, pkg)
	if err != nil {
		return err
	}
	return writeResult(cmd, cmd.OutOrStdout(), result)
}

func runTemplateCalls(cmd *cobra.Command, wd string, config analysis.TemplateCallsConfiguration) error {
	_, pl, err := load.Packages(wd)
	if err != nil {
		return err
	}
	pkg, err := load.Package(wd, pl, config.TemplatesVariables)
	if err != nil {
		return err
	}
	result, err := analysis.NewTemplateCalls(config, pkg)
	if err != nil {
		return err
	}
	return writeResult(cmd, cmd.OutOrStdout(), result)
}

func runTemplateMutations(cmd *cobra.Command, wd string, config mutation.Configuration) error {
	report, err := mutation.Run(config, wd, cmd.ErrOrStderr())
	if err != nil {
		printMultiLineError(cmd, err)
		return err
	}
	return writeResult(cmd, cmd.OutOrStdout(), report)
}

func runGenerate(cmd *cobra.Command, wd string, config generate.RoutesFileConfiguration) error {
	stdout := cmd.OutOrStdout()
	_, pl, err := load.Packages(wd, config.ReceiverPackage)
	if err != nil {
		return err
	}
	warnPartialAST(log.New(cmd.ErrOrStderr(), "", 0), pl)
	pkg, receiver, err := load.GenerateSource(wd, pl, config)
	if err != nil {
		printMultiLineError(cmd, err)
		return err
	}
	files, err := generate.TemplateRoutesFiles(wd, config, pkg, receiver, log.New(stdout, "", 0))
	if err != nil {
		printMultiLineError(cmd, err)
		return err
	}

	// CLEANUP HEURISTIC:
	// We automatically delete muxt-generated files that are no longer needed to avoid
	// manual cleanup when template files are renamed or generation modes change.
	//
	// Files are identified by:
	// 1. Presence of "// Code generated by muxt generate" comment
	// 2. Matching --output-routes-func value (to differentiate multiple route sets)
	//
	// Cleanup scenarios:
	// - Template renamed: old_template_routes_gen.go deleted when template renamed to new.gohtml
	// - Switch to single-file: all per-file *_template_routes_gen.go files deleted
	// - Switch to multi-file: old single template_routes.go overwritten (if same filename)
	// - Routes function unchanged: only deletes files matching current routes function
	//
	// IMPORTANT: If you change --output-routes-func value, old files with the previous
	// routes function name will NOT be deleted (to allow multiple route sets to coexist).
	// To clean up after changing routes function name, manually delete old files or
	// temporarily use the old --output-routes-func value with current templates.

	// Find existing generated files for cleanup
	oldGeneratedFiles, err := generate.FileArguments(wd, config.RoutesFunction)
	if err != nil {
		return err
	}

	for oldFilePath, oldArgs := range oldGeneratedFiles {
		var (
			oldConfig                 generate.RoutesFileConfiguration
			oldDeprecatedTemplatesVar string
		)
		set := pflag.NewFlagSet("parse-old", pflag.ContinueOnError)
		addGenerateFlags(set, &oldConfig, &oldDeprecatedTemplatesVar)
		set.SetOutput(io.Discard)
		if err := set.Parse(oldArgs); err != nil {
			log.Printf("WARNING: ignored generated file %s because arguments failed to parse: %s", oldFilePath, err)
			continue
		}
		if oldConfig.RoutesFunction != config.RoutesFunction {
			delete(oldGeneratedFiles, oldFilePath)
		}
		if oldDeprecatedTemplatesVar != "" {
			oldConfig.TemplatesVariables = []string{oldDeprecatedTemplatesVar}
		}
	}

	// Write new files
	newGeneratedFiles := make(map[string]bool)
	for i, file := range files {
		var sb bytes.Buffer
		writeCodeGenerationComment(&sb, configToArgs(config), config.MuxtVersion)
		sb.WriteString(file.Content)
		if err := os.WriteFile(file.Path, sb.Bytes(), 0o644); err != nil {
			for _, f := range files[:i] {
				if rmErr := os.Remove(f.Path); rmErr != nil {
					err = errors.Join(err, rmErr)
				}
			}
			return err
		}
		// Always include the count — a uniform line parses reliably.
		if file.Routes == 1 {
			_, _ = fmt.Fprintf(stdout, "wrote %s: 1 route\n", filepath.Base(file.Path))
		} else {
			_, _ = fmt.Fprintf(stdout, "wrote %s: %d routes\n", filepath.Base(file.Path), file.Routes)
		}
		newGeneratedFiles[file.Path] = true
	}

	// Clean up orphaned files
	// Only deletes files that match the current routes function name but weren't regenerated
	for oldFile := range oldGeneratedFiles {
		if !newGeneratedFiles[oldFile] {
			if err := os.Remove(oldFile); err != nil && !os.IsNotExist(err) {
				return fmt.Errorf("failed to remove orphaned file %s: %w", oldFile, err)
			}
		}
	}

	return nil
}
