// Package muxttest builds fake muxt.Checkers and type checks Go source in
// memory, for tests of route resolution and generation that should not
// depend on any standard library.
//
// The one muxt.Checker backed by the official standard library is
// load.StandardLibrary. Tests using this package declare stand-in types in
// the source they type check -- a Request, a Context -- and say which of
// them a reserved argument identifier binds to, and which parse from or
// format as text. What they then state is muxt's rule, not the shape of a
// particular net/http.
//
// The fake itself is generated by counterfeiter (internal/muxt/muxtfakes),
// so it answers every question the interface grows; what a test writes here
// is only the answers it cares about.
package muxttest

import (
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"go/types"
	"slices"
	"sort"
	"testing"

	"github.com/typelate/muxt/internal/muxt"
	"github.com/typelate/muxt/internal/muxt/muxtfakes"
)

// FileSet positions every package Check type checks. It is safe for
// concurrent use.
var FileSet = token.NewFileSet()

// Check type checks files, by file name, as the package with import path
// path. The source may import nothing: a type it needs from outside the
// package is declared in it.
func Check(t testing.TB, path string, files map[string]string) *types.Package {
	t.Helper()
	names := make([]string, 0, len(files))
	for name := range files {
		names = append(names, name)
	}
	sort.Strings(names)
	syntax := make([]*ast.File, 0, len(names))
	for _, name := range names {
		file, err := parser.ParseFile(FileSet, name, files[name], parser.SkipObjectResolution)
		if err != nil {
			t.Fatal(err)
		}
		syntax = append(syntax, file)
	}
	config := types.Config{Importer: importerFunc(func(path string) (*types.Package, error) {
		return nil, fmt.Errorf("muxttest source imports %q; declare a stand-in in the package instead", path)
	})}
	pkg, err := config.Check(path, FileSet, syntax, nil)
	if err != nil {
		t.Fatal(err)
	}
	return pkg
}

type importerFunc func(path string) (*types.Package, error)

func (fn importerFunc) Import(path string) (*types.Package, error) { return fn(path) }

// CheckerBuilder says what a test wants the standard library to look
// like. Fake turns that into the generated muxt.Checker fake.
//
// Read a built checker as a sentence: the identifiers it binds, the types
// that parse from text, the type an upload binds to.
type CheckerBuilder struct {
	scope            map[string]types.Type
	fileHeader       types.Type
	rawJSON          types.Type
	textUnmarshalers []types.Type
	textMarshalers   []types.Type
}

// NewChecker starts a checker that answers nothing: every question a route
// asks it fails, which is what a route needing no request value expects.
func NewChecker() *CheckerBuilder {
	return &CheckerBuilder{scope: make(map[string]types.Type)}
}

// standIns are the stand-in type names StandInChecker binds each reserved
// argument identifier to, when the package declares them.
var standIns = []struct {
	identifier string
	typeName   string
	pointer    bool
}{
	{identifier: muxt.TemplateNameScopeIdentifierHTTPRequest, typeName: "Request", pointer: true},
	{identifier: muxt.TemplateNameScopeIdentifierHTTPResponse, typeName: "ResponseWriter"},
	{identifier: muxt.TemplateNameScopeIdentifierContext, typeName: "Context"},
	{identifier: muxt.TemplateNameScopeIdentifierForm, typeName: "Values"},
	{identifier: muxt.TemplateNameScopeIdentifierMultipart, typeName: "Form", pointer: true},
	{identifier: muxt.TemplateNameScopeIdentifierRequestBody, typeName: "Reader"},
}

// StandInChecker binds each reserved argument identifier to the stand-in
// pkg declares for it -- request to *Request, ctx to Context, and so on --
// and binds an upload to *FileHeader and a JSON body to RawMessage when
// they are declared. A type pkg does not declare is left unbound, so a
// route asking for it fails the way one asking for anything unbound does.
func StandInChecker(t testing.TB, pkg *types.Package) *CheckerBuilder {
	t.Helper()
	c := NewChecker()
	for _, standIn := range standIns {
		tp, ok := declared(pkg, standIn.typeName)
		if !ok {
			continue
		}
		if standIn.pointer {
			tp = types.NewPointer(tp)
		}
		c.Binds(standIn.identifier, tp)
	}
	if tp, ok := declared(pkg, "FileHeader"); ok {
		c.UploadsFilesAs(types.NewPointer(tp))
	}
	if tp, ok := declared(pkg, "RawMessage"); ok {
		c.DecodesJSONAs(tp)
	}
	return c
}

// Binds says the reserved argument identifier binds to tp.
func (c *CheckerBuilder) Binds(identifier string, tp types.Type) *CheckerBuilder {
	c.scope[identifier] = tp
	return c
}

// ParsesFromText says a pointer to each type implements
// encoding.TextUnmarshaler, so a request string parses into it.
func (c *CheckerBuilder) ParsesFromText(tps ...types.Type) *CheckerBuilder {
	c.textUnmarshalers = append(c.textUnmarshalers, tps...)
	return c
}

// FormatsAsText says each type implements encoding.TextMarshaler, so a
// route path formats it as a path segment.
func (c *CheckerBuilder) FormatsAsText(tps ...types.Type) *CheckerBuilder {
	c.textMarshalers = append(c.textMarshalers, tps...)
	return c
}

// UploadsFilesAs says tp is the multipart file header type.
func (c *CheckerBuilder) UploadsFilesAs(tp types.Type) *CheckerBuilder {
	c.fileHeader = tp
	return c
}

// DecodesJSONAs says tp is the raw JSON message type.
func (c *CheckerBuilder) DecodesJSONAs(tp types.Type) *CheckerBuilder {
	c.rawJSON = tp
	return c
}

// Fake returns the generated fake answering what the builder was told, and
// failing every other question the way a standard library that does not
// declare the type would.
func (c *CheckerBuilder) Fake() *muxtfakes.FakeChecker {
	fake := new(muxtfakes.FakeChecker)
	fake.ScopeTypeStub = func(identifier string) (types.Type, error) {
		tp, ok := c.scope[identifier]
		if !ok {
			return nil, fmt.Errorf("the checker binds no type to %s", identifier)
		}
		return tp, nil
	}
	fake.FileHeaderStub = answer(c.fileHeader, "multipart file header")
	fake.RawJSONStub = answer(c.rawJSON, "raw JSON message")
	fake.TextUnmarshalerStub = func(tp types.Type) bool { return contains(c.textUnmarshalers, tp) }
	fake.TextMarshalerStub = func(tp types.Type) bool { return contains(c.textMarshalers, tp) }
	return fake
}

func answer(tp types.Type, what string) func() (types.Type, error) {
	return func() (types.Type, error) {
		if tp == nil {
			return nil, fmt.Errorf("the checker has no %s type", what)
		}
		return tp, nil
	}
}

func contains(list []types.Type, tp types.Type) bool {
	return slices.ContainsFunc(list, func(candidate types.Type) bool { return types.Identical(candidate, tp) })
}

func declared(pkg *types.Package, name string) (types.Type, bool) {
	obj := pkg.Scope().Lookup(name)
	if obj == nil {
		return nil, false
	}
	return obj.Type(), true
}

// Lookup returns the type pkg declares as name, failing t when it declares
// none.
func Lookup(t testing.TB, pkg *types.Package, name string) types.Type {
	t.Helper()
	obj := pkg.Scope().Lookup(name)
	if obj == nil {
		t.Fatalf("%s declares no %s", pkg.Path(), name)
	}
	return obj.Type()
}
