// Code generated by muxt generate --use-receiver-type=Server --wire-typelate-sse. DO NOT EDIT.
// muxt version: (devel)

package main

import (
	"bytes"
	"cmp"
	"context"
	"errors"
	"fmt"
	"log/slog"
	"net/http"
	"path"
	"strconv"
	"sync"
	"time"

	"github.com/typelate/sse"
)

type RoutesReceiver interface {
	Clock(ctx context.Context, execute func(time.Time, ...sse.MessageOption) error) error
	Index() string
}

func TemplateRoutes(mux *http.ServeMux, receiver RoutesReceiver) TemplateRoutePaths {
	pathsPrefix := ""
	bytesBufferPool := sync.Pool{New: func() any {
		return bytes.NewBuffer(nil)
	}}
	mux.HandleFunc("GET /time", func(response http.ResponseWriter, request *http.Request) {
		defer func() {
			_ = request.Body.Close()
		}()
		ctx := request.Context()
		stream, ok := sse.New(response, request, http.StatusOK)
		if !ok {
			http.Error(response, "streaming unsupported", http.StatusInternalServerError)
			return
		}
		if err := receiver.Clock(ctx, func(result time.Time, opts ...sse.MessageOption) error {
			if err := request.Context().Err(); err != nil {
				return err
			}
			buf := bytesBufferPool.Get().(*bytes.Buffer)
			buf.Reset()
			defer bytesBufferPool.Put(buf)
			td := SSETemplateData[RoutesReceiver, time.Time]{receiver: receiver, request: request, pathsPrefix: pathsPrefix, result: result}
			if err := templates.ExecuteTemplate(buf, "GET /time sse(Clock(ctx, execute))", &td); err != nil {
				slog.ErrorContext(request.Context(), "failed to render page", slog.String("path", request.URL.Path), slog.String("pattern", request.Pattern), slog.String("error", err.Error()))
				return err
			}
			messageOptions := make([]sse.MessageOption, 0, 3+len(opts))
			if td.id != nil {
				messageOptions = append(messageOptions, sse.WithID(*td.id))
			}
			if td.event != nil {
				messageOptions = append(messageOptions, sse.WithEvent(*td.event))
			}
			if td.retryMilliseconds != nil {
				messageOptions = append(messageOptions, sse.WithRetry(time.Duration(*td.retryMilliseconds)*time.Millisecond))
			}
			messageOptions = append(messageOptions, opts...)
			return stream.Message(buf.Bytes(), messageOptions...)
		}); err != nil {
			slog.ErrorContext(request.Context(), "sse handler returned an error", slog.String("path", request.URL.Path), slog.String("pattern", request.Pattern), slog.String("error", err.Error()))
		}
	})
	mux.HandleFunc("GET /{$}", func(response http.ResponseWriter, request *http.Request) {
		var td = TemplateData[RoutesReceiver, string]{receiver: receiver, response: response, request: request, pathsPrefix: pathsPrefix}
		buf := bytesBufferPool.Get().(*bytes.Buffer)
		buf.Reset()
		defer bytesBufferPool.Put(buf)
		if len(td.errList) == 0 {
			td.result = receiver.Index()
			td.okay = true
		}
		if err := templates.ExecuteTemplate(buf, "GET /{$} Index()", &td); err != nil {
			slog.ErrorContext(request.Context(), "failed to render page", slog.String("path", request.URL.Path), slog.String("pattern", request.Pattern), slog.String("error", err.Error()))
			http.Error(response, "failed to render page", http.StatusInternalServerError)
			return
		}
		defaultStatusCode := http.StatusOK
		if buf.Len() == 0 {
			defaultStatusCode = http.StatusNoContent
		}
		statusCode := cmp.Or(td.statusCode, td.errStatusCode, defaultStatusCode)
		if td.redirectURL != "" {
			http.Redirect(response, request, td.redirectURL, statusCode)
			return
		}
		if contentType := response.Header().Get("content-type"); contentType == "" {
			response.Header().Set("content-type", "text/html; charset=utf-8")
		}
		response.Header().Set("content-length", strconv.Itoa(buf.Len()))
		response.WriteHeader(statusCode)
		_, _ = buf.WriteTo(response)
	})
	return TemplateRoutePaths{pathsPrefix: pathsPrefix}
}

type TemplateData[R any, T any] struct {
	receiver      R
	response      http.ResponseWriter
	request       *http.Request
	result        T
	statusCode    int
	errStatusCode int
	okay          bool
	errList       []error
	redirectURL   string
	pathsPrefix   string
}

func (data *TemplateData[R, T]) MuxtVersion() string {
	const muxtVersion = "(devel)"
	return muxtVersion
}

func (data *TemplateData[R, T]) Path() TemplateRoutePaths {
	return TemplateRoutePaths{pathsPrefix: data.pathsPrefix}
}

func (data *TemplateData[R, T]) Result() T {
	return data.result
}

func (data *TemplateData[R, T]) Request() *http.Request {
	return data.request
}

func (data *TemplateData[R, T]) StatusCode(statusCode int) *TemplateData[R, T] {
	data.statusCode = statusCode
	return data
}

func (data *TemplateData[R, T]) Header(key, value string) *TemplateData[R, T] {
	data.response.Header().Set(key, value)
	return data
}

func (data *TemplateData[R, T]) Ok() bool {
	return data.okay
}

func (data *TemplateData[R, T]) Err() error {
	return errors.Join(data.errList...)
}

func (data *TemplateData[R, T]) Receiver() R {
	return data.receiver
}

func (data *TemplateData[R, T]) Redirect(url string, code int) (*TemplateData[R, T], error) {
	if code < 300 || code >= 400 {
		return data, fmt.Errorf("invalid status code %d for redirect", code)
	}
	data.redirectURL = url
	return data.StatusCode(code), nil
}

func (data *TemplateData[R, T]) RedirectMultipleChoices(url string) (*TemplateData[R, T], error) {
	return data.Redirect(url, http.StatusMultipleChoices)
}

func (data *TemplateData[R, T]) RedirectMovedPermanently(url string) (*TemplateData[R, T], error) {
	return data.Redirect(url, http.StatusMovedPermanently)
}

func (data *TemplateData[R, T]) RedirectFound(url string) (*TemplateData[R, T], error) {
	return data.Redirect(url, http.StatusFound)
}

func (data *TemplateData[R, T]) RedirectSeeOther(url string) (*TemplateData[R, T], error) {
	return data.Redirect(url, http.StatusSeeOther)
}

func (data *TemplateData[R, T]) String() string {
	return ""
}

type SSETemplateData[R, T any] struct {
	receiver          R
	request           *http.Request
	result            T
	pathsPrefix       string
	event, id         *string
	retryMilliseconds *int
	errList           []error
	data              *bytes.Buffer
}

func (m *SSETemplateData[R, T]) String() string {
	return ""
}

func (m *SSETemplateData[R, T]) Receiver() R {
	return m.receiver
}

func (m *SSETemplateData[R, T]) Request() *http.Request {
	return m.request
}

func (m *SSETemplateData[R, T]) Result() T {
	return m.result
}

func (m *SSETemplateData[R, T]) Err() error {
	return errors.Join(m.errList...)
}

func (m *SSETemplateData[R, T]) Event(event string) *SSETemplateData[R, T] {
	m.event = &event
	return m
}

func (m *SSETemplateData[R, T]) ID(id string) *SSETemplateData[R, T] {
	m.id = &id
	return m
}

func (m *SSETemplateData[R, T]) Retry(retryMilliseconds int) *SSETemplateData[R, T] {
	m.retryMilliseconds = &retryMilliseconds
	return m
}

func (m *SSETemplateData[R, T]) Path() TemplateRoutePaths {
	return TemplateRoutePaths{pathsPrefix: m.pathsPrefix}
}

type TemplateRoutePaths struct {
	pathsPrefix string
}

func (routePaths TemplateRoutePaths) Clock() string {
	return path.Join(cmp.Or(routePaths.pathsPrefix, "/"), "time")
}

func (routePaths TemplateRoutePaths) Index() string {
	return "/"
}
