// Code generated by muxt generate --use-receiver-type=Server --use-datastar. DO NOT EDIT.
// muxt version: (devel)

package main

import (
	"bytes"
	"cmp"
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"html/template"
	"io"
	"log/slog"
	"net/http"
	"path"
	"strconv"
	"strings"
	"sync"
	"time"
)

type RoutesReceiver interface {
	Home(_ context.Context) (int64, error)
	Greet(_ context.Context, signals GreetSignals, sendGreeting func(string) error)
	Increment(_ context.Context, sendCount func(int64) error)
}

func TemplateRoutes(mux *http.ServeMux, receiver RoutesReceiver) TemplateRoutePaths {
	pathsPrefix := ""
	bytesBufferPool := sync.Pool{New: func() any {
		return bytes.NewBuffer(nil)
	}}
	mux.HandleFunc("GET /", func(response http.ResponseWriter, request *http.Request) {
		var td = DatastarTemplateData[RoutesReceiver, int64]{receiver: receiver, response: response, request: request, pathsPrefix: pathsPrefix}
		ctx := request.Context()
		buf := bytesBufferPool.Get().(*bytes.Buffer)
		buf.Reset()
		defer bytesBufferPool.Put(buf)
		if len(td.errList) == 0 {
			var err error
			td.result, err = receiver.Home(ctx)
			if err != nil {
				td.errList = append(td.errList, err)
				td.errStatusCode = http.StatusInternalServerError
			}
		}
		if err := templates.ExecuteTemplate(buf, "GET / Home(ctx)", &td); err != nil {
			slog.ErrorContext(request.Context(), "failed to render page", slog.String("path", request.URL.Path), slog.String("pattern", request.Pattern), slog.String("error", err.Error()))
			http.Error(response, "failed to render page", http.StatusInternalServerError)
			return
		}
		defaultStatusCode := http.StatusOK
		if buf.Len() == 0 {
			defaultStatusCode = http.StatusNoContent
		}
		statusCode := cmp.Or(td.statusCode, td.errStatusCode, defaultStatusCode)
		if td.redirectURL != "" {
			http.Redirect(response, request, td.redirectURL, statusCode)
			return
		}
		if contentType := response.Header().Get("content-type"); contentType == "" {
			response.Header().Set("content-type", "text/html; charset=utf-8")
		}
		response.Header().Set("content-length", strconv.Itoa(buf.Len()))
		response.WriteHeader(statusCode)
		_, _ = buf.WriteTo(response)
	})
	mux.HandleFunc("POST /greet", func(response http.ResponseWriter, request *http.Request) {
		defer func() {
			_ = request.Body.Close()
		}()
		flusher, ok := response.(http.Flusher)
		if !ok {
			http.Error(response, "streaming unsupported", http.StatusInternalServerError)
			return
		}
		ctx := request.Context()
		var signalsValue GreetSignals
		if err := json.NewDecoder(request.Body).Decode(&signalsValue); err != nil && !errors.Is(err, io.EOF) {
			http.Error(response, err.Error(), http.StatusBadRequest)
			return
		}
		h := response.Header()
		h.Set("Content-Type", "text/event-stream")
		h.Set("Connection", "keep-alive")
		h.Set("Cache-Control", "no-store")
		response.WriteHeader(http.StatusOK)
		flusher.Flush()
		var mut sync.Mutex
		receiver.Greet(ctx, signalsValue, func(result string) error {
			if err := request.Context().Err(); err != nil {
				return err
			}
			buf := bytesBufferPool.Get().(*bytes.Buffer)
			buf.Reset()
			defer bytesBufferPool.Put(buf)
			td := DatastarEventTemplateData[RoutesReceiver, string]{receiver: receiver, request: request, pathsPrefix: pathsPrefix, result: result}
			if err := templates.ExecuteTemplate(buf, "Greeting", &td); err != nil {
				slog.ErrorContext(request.Context(), "failed to render page", slog.String("path", request.URL.Path), slog.String("pattern", request.Pattern), slog.String("error", err.Error()))
				return err
			}
			td.data = buf
			mut.Lock()
			defer mut.Unlock()
			if _, err := td.WriteTo(response); err != nil {
				return err
			}
			flusher.Flush()
			return nil
		})
	})
	mux.HandleFunc("POST /increment", func(response http.ResponseWriter, request *http.Request) {
		defer func() {
			_ = request.Body.Close()
		}()
		flusher, ok := response.(http.Flusher)
		if !ok {
			http.Error(response, "streaming unsupported", http.StatusInternalServerError)
			return
		}
		ctx := request.Context()
		h := response.Header()
		h.Set("Content-Type", "text/event-stream")
		h.Set("Connection", "keep-alive")
		h.Set("Cache-Control", "no-store")
		response.WriteHeader(http.StatusOK)
		flusher.Flush()
		var mut sync.Mutex
		receiver.Increment(ctx, func(result int64) error {
			if err := request.Context().Err(); err != nil {
				return err
			}
			buf := bytesBufferPool.Get().(*bytes.Buffer)
			buf.Reset()
			defer bytesBufferPool.Put(buf)
			td := DatastarEventTemplateData[RoutesReceiver, int64]{receiver: receiver, request: request, pathsPrefix: pathsPrefix, result: result}
			if err := templates.ExecuteTemplate(buf, "Count", &td); err != nil {
				slog.ErrorContext(request.Context(), "failed to render page", slog.String("path", request.URL.Path), slog.String("pattern", request.Pattern), slog.String("error", err.Error()))
				return err
			}
			td.data = buf
			mut.Lock()
			defer mut.Unlock()
			if _, err := td.WriteTo(response); err != nil {
				return err
			}
			flusher.Flush()
			return nil
		})
	})
	return TemplateRoutePaths{pathsPrefix: pathsPrefix}
}

type DatastarTemplateData[R any, T any] struct {
	receiver      R
	response      http.ResponseWriter
	request       *http.Request
	result        T
	statusCode    int
	errStatusCode int
	okay          bool
	errList       []error
	redirectURL   string
	pathsPrefix   string
}

func (data *DatastarTemplateData[R, T]) MuxtVersion() string {
	const muxtVersion = "(devel)"
	return muxtVersion
}

func (data *DatastarTemplateData[R, T]) Path() TemplateRoutePaths {
	return TemplateRoutePaths{pathsPrefix: data.pathsPrefix}
}

func (data *DatastarTemplateData[R, T]) Result() T {
	return data.result
}

func (data *DatastarTemplateData[R, T]) Request() *http.Request {
	return data.request
}

func (data *DatastarTemplateData[R, T]) StatusCode(statusCode int) *DatastarTemplateData[R, T] {
	data.statusCode = statusCode
	return data
}

func (data *DatastarTemplateData[R, T]) Header(key, value string) *DatastarTemplateData[R, T] {
	data.response.Header().Set(key, value)
	return data
}

func (data *DatastarTemplateData[R, T]) Ok() bool {
	return data.okay
}

func (data *DatastarTemplateData[R, T]) Err() error {
	return errors.Join(data.errList...)
}

func (data *DatastarTemplateData[R, T]) Receiver() R {
	return data.receiver
}

func (data *DatastarTemplateData[R, T]) Redirect(url string, code int) (*DatastarTemplateData[R, T], error) {
	if code < 300 || code >= 400 {
		return data, fmt.Errorf("invalid status code %d for redirect", code)
	}
	data.redirectURL = url
	return data.StatusCode(code), nil
}

func (data *DatastarTemplateData[R, T]) RedirectMultipleChoices(url string) (*DatastarTemplateData[R, T], error) {
	return data.Redirect(url, http.StatusMultipleChoices)
}

func (data *DatastarTemplateData[R, T]) RedirectMovedPermanently(url string) (*DatastarTemplateData[R, T], error) {
	return data.Redirect(url, http.StatusMovedPermanently)
}

func (data *DatastarTemplateData[R, T]) RedirectFound(url string) (*DatastarTemplateData[R, T], error) {
	return data.Redirect(url, http.StatusFound)
}

func (data *DatastarTemplateData[R, T]) RedirectSeeOther(url string) (*DatastarTemplateData[R, T], error) {
	return data.Redirect(url, http.StatusSeeOther)
}

func (data *DatastarTemplateData[R, T]) String() string {
	return ""
}

type DatastarEventTemplateData[R, T any] struct {
	receiver                                    R
	request                                     *http.Request
	result                                      T
	pathsPrefix                                 string
	event, id                                   *string
	retryMilliseconds                           *int
	errList                                     []error
	data                                        *bytes.Buffer
	selector, mode, namespace                   *string
	useViewTransition, onlyIfMissing, isSignals bool
}

func (m *DatastarEventTemplateData[R, T]) String() string {
	return ""
}

func (m *DatastarEventTemplateData[R, T]) Receiver() R {
	return m.receiver
}

func (m *DatastarEventTemplateData[R, T]) Request() *http.Request {
	return m.request
}

func (m *DatastarEventTemplateData[R, T]) Result() T {
	return m.result
}

func (m *DatastarEventTemplateData[R, T]) Err() error {
	return errors.Join(m.errList...)
}

func (m *DatastarEventTemplateData[R, T]) ID(id string) *DatastarEventTemplateData[R, T] {
	m.id = &id
	return m
}

func (m *DatastarEventTemplateData[R, T]) Retry(retryMilliseconds int) *DatastarEventTemplateData[R, T] {
	m.retryMilliseconds = &retryMilliseconds
	return m
}

func (m *DatastarEventTemplateData[R, T]) Path() TemplateRoutePaths {
	return TemplateRoutePaths{pathsPrefix: m.pathsPrefix}
}

func (m *DatastarEventTemplateData[R, T]) Selector(selector string) *DatastarEventTemplateData[R, T] {
	m.selector = &selector
	return m
}

func (m *DatastarEventTemplateData[R, T]) Mode(mode string) *DatastarEventTemplateData[R, T] {
	m.mode = &mode
	return m
}

func (m *DatastarEventTemplateData[R, T]) Namespace(namespace string) *DatastarEventTemplateData[R, T] {
	m.namespace = &namespace
	return m
}

func (m *DatastarEventTemplateData[R, T]) UseViewTransition(value bool) *DatastarEventTemplateData[R, T] {
	m.useViewTransition = value
	return m
}

func (m *DatastarEventTemplateData[R, T]) OnlyIfMissing(value bool) *DatastarEventTemplateData[R, T] {
	m.onlyIfMissing = value
	return m
}

func (m *DatastarEventTemplateData[R, T]) WriteTo(w io.Writer) (int64, error) {
	if m.id != nil && strings.ContainsAny(*m.id, "\r\n\x00") {
		return 0, errors.New("sse: id contains a forbidden character")
	}
	var bytesWritten int
	eventType, dataPrefix := "datastar-patch-elements", "data: elements "
	if m.isSignals {
		eventType, dataPrefix = "datastar-patch-signals", "data: signals "
	}
	if n, err := io.WriteString(w, "event: "); err != nil {
		return int64(bytesWritten + n), err
	} else {
		bytesWritten += n
	}
	if n, err := io.WriteString(w, eventType); err != nil {
		return int64(bytesWritten + n), err
	} else {
		bytesWritten += n
	}
	if n, err := w.Write([]byte{'\n'}); err != nil {
		return int64(bytesWritten + n), err
	} else {
		bytesWritten += n
	}
	if m.id != nil {
		if n, err := io.WriteString(w, "id: "); err != nil {
			return int64(bytesWritten + n), err
		} else {
			bytesWritten += n
		}
		if n, err := io.WriteString(w, *m.id); err != nil {
			return int64(bytesWritten + n), err
		} else {
			bytesWritten += n
		}
		if n, err := w.Write([]byte{'\n'}); err != nil {
			return int64(bytesWritten + n), err
		} else {
			bytesWritten += n
		}
	}
	if m.retryMilliseconds != nil {
		if n, err := io.WriteString(w, "retry: "); err != nil {
			return int64(bytesWritten + n), err
		} else {
			bytesWritten += n
		}
		var retryBuf [20]byte
		if n, err := w.Write(strconv.AppendInt(retryBuf[:0], int64(*m.retryMilliseconds), 10)); err != nil {
			return int64(bytesWritten + n), err
		} else {
			bytesWritten += n
		}
		if n, err := w.Write([]byte{'\n'}); err != nil {
			return int64(bytesWritten + n), err
		} else {
			bytesWritten += n
		}
	}
	if !m.isSignals {
		if m.selector != nil {
			if n, err := io.WriteString(w, "data: selector "); err != nil {
				return int64(bytesWritten + n), err
			} else {
				bytesWritten += n
			}
			if n, err := io.WriteString(w, *m.selector); err != nil {
				return int64(bytesWritten + n), err
			} else {
				bytesWritten += n
			}
			if n, err := w.Write([]byte{'\n'}); err != nil {
				return int64(bytesWritten + n), err
			} else {
				bytesWritten += n
			}
		}
		if m.mode != nil {
			if n, err := io.WriteString(w, "data: mode "); err != nil {
				return int64(bytesWritten + n), err
			} else {
				bytesWritten += n
			}
			if n, err := io.WriteString(w, *m.mode); err != nil {
				return int64(bytesWritten + n), err
			} else {
				bytesWritten += n
			}
			if n, err := w.Write([]byte{'\n'}); err != nil {
				return int64(bytesWritten + n), err
			} else {
				bytesWritten += n
			}
		}
		if m.namespace != nil {
			if n, err := io.WriteString(w, "data: namespace "); err != nil {
				return int64(bytesWritten + n), err
			} else {
				bytesWritten += n
			}
			if n, err := io.WriteString(w, *m.namespace); err != nil {
				return int64(bytesWritten + n), err
			} else {
				bytesWritten += n
			}
			if n, err := w.Write([]byte{'\n'}); err != nil {
				return int64(bytesWritten + n), err
			} else {
				bytesWritten += n
			}
		}
		if m.useViewTransition {
			if n, err := io.WriteString(w, "data: useViewTransition true\n"); err != nil {
				return int64(bytesWritten + n), err
			} else {
				bytesWritten += n
			}
		}
	} else {
		if m.onlyIfMissing {
			if n, err := io.WriteString(w, "data: onlyIfMissing true\n"); err != nil {
				return int64(bytesWritten + n), err
			} else {
				bytesWritten += n
			}
		}
	}
	data := m.data.Bytes()
	if bytes.IndexByte(data, '\r') >= 0 {
		data = bytes.ReplaceAll(data, []byte("\r\n"), []byte("\n"))
		data = bytes.ReplaceAll(data, []byte("\r"), []byte("\n"))
	}
	data = bytes.TrimSuffix(data, []byte{'\n'})
	for line := range bytes.SplitSeq(data, []byte{'\n'}) {
		if n, err := io.WriteString(w, dataPrefix); err != nil {
			return int64(bytesWritten + n), err
		} else {
			bytesWritten += n
		}
		if n, err := w.Write(line); err != nil {
			return int64(bytesWritten + n), err
		} else {
			bytesWritten += n
		}
		if n, err := w.Write([]byte{'\n'}); err != nil {
			return int64(bytesWritten + n), err
		} else {
			bytesWritten += n
		}
	}
	if n, err := w.Write([]byte{'\n', '\n'}); err != nil {
		return int64(bytesWritten + n), err
	} else {
		bytesWritten += n
	}
	return int64(bytesWritten), nil
}

type SSEEventOption func(sseEventConfigurer)
type sseEventConfigurer interface {
	setEvent(string)
	setEventID(string)
	setRetry(int)
	setSelector(string)
	setMode(string)
	setNamespace(string)
	setUseViewTransition(bool)
	setOnlyIfMissing(bool)
}

func WithEvent(event string) func(sseEventConfigurer) {
	return func(c sseEventConfigurer) {
		c.setEvent(event)
	}
}

func WithEventID(id string) func(sseEventConfigurer) {
	return func(c sseEventConfigurer) {
		c.setEventID(id)
	}
}

func WithRetryDuration(retryDuration time.Duration) func(sseEventConfigurer) {
	return func(c sseEventConfigurer) {
		c.setRetry(int(retryDuration.Milliseconds()))
	}
}

type DatastarPatchElementOption func(sseEventConfigurer)
type DatastarPatchSignalsOption func(sseEventConfigurer)

func WithSelector(selector string) func(sseEventConfigurer) {
	return func(c sseEventConfigurer) {
		c.setSelector(selector)
	}
}

func WithSelectorID(id string) func(sseEventConfigurer) {
	return func(c sseEventConfigurer) {
		c.setSelector("#" + id)
	}
}

func WithMode(mode string) func(sseEventConfigurer) {
	return func(c sseEventConfigurer) {
		c.setMode(mode)
	}
}

func WithNamespace(namespace string) func(sseEventConfigurer) {
	return func(c sseEventConfigurer) {
		c.setNamespace(namespace)
	}
}

func WithUseViewTransition(useViewTransition bool) func(sseEventConfigurer) {
	return func(c sseEventConfigurer) {
		c.setUseViewTransition(useViewTransition)
	}
}

func WithOnlyIfMissing(onlyIfMissing bool) func(sseEventConfigurer) {
	return func(c sseEventConfigurer) {
		c.setOnlyIfMissing(onlyIfMissing)
	}
}

func (m *DatastarEventTemplateData[R, T]) setEvent(event string) {
	m.event = &event
}

func (m *DatastarEventTemplateData[R, T]) setEventID(id string) {
	m.id = &id
}

func (m *DatastarEventTemplateData[R, T]) setRetry(retry int) {
	m.retryMilliseconds = &retry
}

func (m *DatastarEventTemplateData[R, T]) setSelector(selector string) {
	m.selector = &selector
}

func (m *DatastarEventTemplateData[R, T]) setMode(mode string) {
	m.mode = &mode
}

func (m *DatastarEventTemplateData[R, T]) setNamespace(namespace string) {
	m.namespace = &namespace
}

func (m *DatastarEventTemplateData[R, T]) setUseViewTransition(value bool) {
	m.useViewTransition = value
}

func (m *DatastarEventTemplateData[R, T]) setOnlyIfMissing(value bool) {
	m.onlyIfMissing = value
}

type DatastarActions struct {
	pathsPrefix string
}
type DatastarAction struct {
	method, url         string
	contentType         *string
	openWhenHidden      *bool
	selector            *string
	retry               *string
	requestCancellation *string
	retryInterval       *int
	retryScaler         *float64
	retryMaxWait        *int
	retryMaxCount       *int
}

func (actions DatastarActions) Home() DatastarAction {
	return DatastarAction{method: "get", url: path.Join(cmp.Or(actions.pathsPrefix, "/"))}
}

func (actions DatastarActions) Greet() DatastarAction {
	return DatastarAction{method: "post", url: path.Join(cmp.Or(actions.pathsPrefix, "/"), "greet")}
}

func (actions DatastarActions) Increment() DatastarAction {
	return DatastarAction{method: "post", url: path.Join(cmp.Or(actions.pathsPrefix, "/"), "increment")}
}

func (action DatastarAction) ContentType(value string) DatastarAction {
	action.contentType = &value
	return action
}

func (action DatastarAction) OpenWhenHidden(value bool) DatastarAction {
	action.openWhenHidden = &value
	return action
}

func (action DatastarAction) Selector(value string) DatastarAction {
	action.selector = &value
	return action
}

func (action DatastarAction) Retry(value string) DatastarAction {
	action.retry = &value
	return action
}

func (action DatastarAction) RequestCancellation(value string) DatastarAction {
	action.requestCancellation = &value
	return action
}

func (action DatastarAction) RetryInterval(value int) DatastarAction {
	action.retryInterval = &value
	return action
}

func (action DatastarAction) RetryScaler(value float64) DatastarAction {
	action.retryScaler = &value
	return action
}

func (action DatastarAction) RetryMaxWait(value int) DatastarAction {
	action.retryMaxWait = &value
	return action
}

func (action DatastarAction) RetryMaxCount(value int) DatastarAction {
	action.retryMaxCount = &value
	return action
}

func (action DatastarAction) URL() string {
	return action.url
}

func (action DatastarAction) js() template.JS {
	return template.JS("@" + action.method + "('" + template.JSEscapeString(action.url) + "'" + action.optionsObject() + ")")
}

func (action DatastarAction) optionsObject() string {
	var parts []string
	if action.contentType != nil {
		parts = append(parts, "contentType: "+("'"+template.JSEscapeString(*action.contentType)+"'"))
	}
	if action.openWhenHidden != nil {
		parts = append(parts, "openWhenHidden: "+strconv.FormatBool(*action.openWhenHidden))
	}
	if action.selector != nil {
		parts = append(parts, "selector: "+("'"+template.JSEscapeString(*action.selector)+"'"))
	}
	if action.retry != nil {
		parts = append(parts, "retry: "+("'"+template.JSEscapeString(*action.retry)+"'"))
	}
	if action.requestCancellation != nil {
		parts = append(parts, "requestCancellation: "+("'"+template.JSEscapeString(*action.requestCancellation)+"'"))
	}
	if action.retryInterval != nil {
		parts = append(parts, "retryInterval: "+strconv.Itoa(*action.retryInterval))
	}
	if action.retryScaler != nil {
		parts = append(parts, "retryScaler: "+strconv.FormatFloat(*action.retryScaler, 'g', -1, 64))
	}
	if action.retryMaxWait != nil {
		parts = append(parts, "retryMaxWait: "+strconv.Itoa(*action.retryMaxWait))
	}
	if action.retryMaxCount != nil {
		parts = append(parts, "retryMaxCount: "+strconv.Itoa(*action.retryMaxCount))
	}
	if len(parts) == 0 {
		return ""
	}
	return ", {" + strings.Join(parts, ", ") + "}"
}

func (data *DatastarTemplateData[R, T]) Actions() DatastarActions {
	return DatastarActions{pathsPrefix: data.pathsPrefix}
}

func (data *DatastarTemplateData[R, T]) JS(action DatastarAction) template.JS {
	return action.js()
}

func (m *DatastarEventTemplateData[R, T]) Actions() DatastarActions {
	return DatastarActions{pathsPrefix: m.pathsPrefix}
}

func (m *DatastarEventTemplateData[R, T]) JS(action DatastarAction) template.JS {
	return action.js()
}

type TemplateRoutePaths struct {
	pathsPrefix string
}

func (routePaths TemplateRoutePaths) Home() string {
	return "/"
}

func (routePaths TemplateRoutePaths) Greet() string {
	return path.Join(cmp.Or(routePaths.pathsPrefix, "/"), "greet")
}

func (routePaths TemplateRoutePaths) Increment() string {
	return path.Join(cmp.Or(routePaths.pathsPrefix, "/"), "increment")
}
