// Code generated by muxt generate --use-receiver-type=Server --use-datastar. DO NOT EDIT.
// muxt version: (devel)

package main

import (
	"bytes"
	"cmp"
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"html/template"
	"io"
	"log/slog"
	"net/http"
	"path"
	"strconv"
	"strings"
	"sync"
)

type RoutesReceiver interface {
	Index() any
	Clock(ctx context.Context, elements func(string) error)
	Hello(ctx context.Context, script func() error)
	Increment(ctx context.Context, signal func(Count, bool) error)
}

func TemplateRoutes(mux *http.ServeMux, receiver RoutesReceiver) TemplateRoutePaths {
	pathsPrefix := ""
	bytesBufferPool := sync.Pool{New: func() any {
		return bytes.NewBuffer(nil)
	}}
	mux.HandleFunc("GET /", func(response http.ResponseWriter, request *http.Request) {
		var td = DatastarTemplateData[RoutesReceiver, any]{receiver: receiver, response: response, request: request, pathsPrefix: pathsPrefix}
		buf := bytesBufferPool.Get().(*bytes.Buffer)
		buf.Reset()
		defer bytesBufferPool.Put(buf)
		if len(td.errList) == 0 {
			td.result = receiver.Index()
			td.okay = true
		}
		if err := templates.ExecuteTemplate(buf, "GET / Index()", &td); err != nil {
			slog.ErrorContext(request.Context(), "failed to render page", slog.String("path", request.URL.Path), slog.String("pattern", request.Pattern), slog.String("error", err.Error()))
			http.Error(response, "failed to render page", http.StatusInternalServerError)
			return
		}
		defaultStatusCode := http.StatusOK
		if buf.Len() == 0 {
			defaultStatusCode = http.StatusNoContent
		}
		statusCode := cmp.Or(td.statusCode, td.errStatusCode, defaultStatusCode)
		if contentType := response.Header().Get("content-type"); contentType == "" {
			response.Header().Set("content-type", "text/html; charset=utf-8")
		}
		response.Header().Set("content-length", strconv.Itoa(buf.Len()))
		response.WriteHeader(statusCode)
		_, _ = buf.WriteTo(response)
	})
	mux.HandleFunc("GET /clock", func(response http.ResponseWriter, request *http.Request) {
		defer func() {
			_ = request.Body.Close()
		}()
		flusher, ok := response.(http.Flusher)
		if !ok {
			http.Error(response, "streaming unsupported", http.StatusInternalServerError)
			return
		}
		ctx := request.Context()
		h := response.Header()
		h.Set("Content-Type", "text/event-stream")
		h.Set("Connection", "keep-alive")
		h.Set("Cache-Control", "no-cache")
		response.WriteHeader(http.StatusOK)
		flusher.Flush()
		var mut sync.Mutex
		receiver.Clock(ctx, func(result string) error {
			if err := request.Context().Err(); err != nil {
				return err
			}
			buf := bytesBufferPool.Get().(*bytes.Buffer)
			buf.Reset()
			defer bytesBufferPool.Put(buf)
			td := DatastarEventTemplateData[RoutesReceiver, string]{receiver: receiver, request: request, pathsPrefix: pathsPrefix, result: result}
			if err := templates.ExecuteTemplate(buf, "GET /clock Clock(ctx, elements)", &td); err != nil {
				slog.ErrorContext(request.Context(), "failed to render page", slog.String("path", request.URL.Path), slog.String("pattern", request.Pattern), slog.String("error", err.Error()))
				return err
			}
			td.data = buf
			mut.Lock()
			defer mut.Unlock()
			if _, err := td.WriteTo(response); err != nil {
				return err
			}
			flusher.Flush()
			return nil
		})
	})
	mux.HandleFunc("GET /hello.js", func(response http.ResponseWriter, request *http.Request) {
		defer func() {
			_ = request.Body.Close()
		}()
		ctx := request.Context()
		response.Header().Set("Content-Type", "text/javascript")
		receiver.Hello(ctx, func() error {
			buf := bytesBufferPool.Get().(*bytes.Buffer)
			buf.Reset()
			defer bytesBufferPool.Put(buf)
			td := DatastarTemplateData[RoutesReceiver, struct{}]{receiver: receiver, response: response, request: request, pathsPrefix: pathsPrefix}
			if err := templates.ExecuteTemplate(buf, "GET /hello.js Hello(ctx, script)", &td); err != nil {
				slog.ErrorContext(request.Context(), "failed to render page", slog.String("path", request.URL.Path), slog.String("pattern", request.Pattern), slog.String("error", err.Error()))
				return err
			}
			_, err := response.Write(buf.Bytes())
			return err
		})
	})
	mux.HandleFunc("POST /increment", func(response http.ResponseWriter, request *http.Request) {
		defer func() {
			_ = request.Body.Close()
		}()
		ctx := request.Context()
		response.Header().Set("Content-Type", "application/json")
		receiver.Increment(ctx, func(result Count, onlyIfMissing bool) error {
			buf := bytesBufferPool.Get().(*bytes.Buffer)
			buf.Reset()
			defer bytesBufferPool.Put(buf)
			_ = onlyIfMissing
			if err := datastarMarshalSignals(buf, result); err != nil {
				return err
			}
			_, err := response.Write(buf.Bytes())
			return err
		})
	})
	return TemplateRoutePaths{pathsPrefix: pathsPrefix}
}

type DatastarTemplateData[R any, T any] struct {
	receiver      R
	response      http.ResponseWriter
	request       *http.Request
	result        T
	statusCode    int
	errStatusCode int
	okay          bool
	errList       []error
	redirectURL   string
	pathsPrefix   string
}

func (data *DatastarTemplateData[R, T]) MuxtVersion() string {
	const muxtVersion = "(devel)"
	return muxtVersion
}

func (data *DatastarTemplateData[R, T]) Path() TemplateRoutePaths {
	return TemplateRoutePaths{pathsPrefix: data.pathsPrefix}
}

func (data *DatastarTemplateData[R, T]) Result() T {
	return data.result
}

func (data *DatastarTemplateData[R, T]) Request() *http.Request {
	return data.request
}

func (data *DatastarTemplateData[R, T]) StatusCode(statusCode int) *DatastarTemplateData[R, T] {
	data.statusCode = statusCode
	return data
}

func (data *DatastarTemplateData[R, T]) Header(key, value string) *DatastarTemplateData[R, T] {
	data.response.Header().Set(key, value)
	return data
}

func (data *DatastarTemplateData[R, T]) Ok() bool {
	return data.okay
}

func (data *DatastarTemplateData[R, T]) Err() error {
	return errors.Join(data.errList...)
}

func (data *DatastarTemplateData[R, T]) Receiver() R {
	return data.receiver
}

func (data *DatastarTemplateData[R, T]) Redirect(url string, code int) (*DatastarTemplateData[R, T], error) {
	if code < 300 || code >= 400 {
		return data, fmt.Errorf("invalid status code %d for redirect", code)
	}
	data.redirectURL = url
	return data.StatusCode(code), nil
}

func (data *DatastarTemplateData[R, T]) RedirectMultipleChoices(url string) (*DatastarTemplateData[R, T], error) {
	return data.Redirect(url, http.StatusMultipleChoices)
}

func (data *DatastarTemplateData[R, T]) RedirectMovedPermanently(url string) (*DatastarTemplateData[R, T], error) {
	return data.Redirect(url, http.StatusMovedPermanently)
}

func (data *DatastarTemplateData[R, T]) RedirectFound(url string) (*DatastarTemplateData[R, T], error) {
	return data.Redirect(url, http.StatusFound)
}

func (data *DatastarTemplateData[R, T]) RedirectSeeOther(url string) (*DatastarTemplateData[R, T], error) {
	return data.Redirect(url, http.StatusSeeOther)
}

func (data *DatastarTemplateData[R, T]) String() string {
	return ""
}

func (data *DatastarTemplateData[R, T]) Actions() DatastarActions {
	return DatastarActions{pathsPrefix: data.pathsPrefix}
}

type DatastarActions struct {
	pathsPrefix string
}

func (routeActions DatastarActions) Index() DatastarAction {
	return newDatastarAction("@get", TemplateRoutePaths(routeActions).Index())
}

func (routeActions DatastarActions) Clock() DatastarAction {
	return newDatastarAction("@get", TemplateRoutePaths(routeActions).Clock())
}

func (routeActions DatastarActions) Hello() DatastarAction {
	return newDatastarAction("@get", TemplateRoutePaths(routeActions).Hello())
}

func (routeActions DatastarActions) Increment() DatastarAction {
	return newDatastarAction("@post", TemplateRoutePaths(routeActions).Increment())
}

type DatastarAction struct {
	verb    string
	url     string
	options []string
}

func newDatastarAction(verb, url string) DatastarAction {
	return DatastarAction{verb: verb, url: url}
}

func (a DatastarAction) with(option string) DatastarAction {
	a.options = append(append(make([]string, 0, len(a.options)+1), a.options...), option)
	return a
}

func (a DatastarAction) ContentType(contentType string) DatastarAction {
	return a.with("contentType: " + datastarJSString(contentType))
}

func (a DatastarAction) OpenWhenHidden(openWhenHidden bool) DatastarAction {
	return a.with("openWhenHidden: " + strconv.FormatBool(openWhenHidden))
}

func (a DatastarAction) Selector(selector string) DatastarAction {
	return a.with("selector: " + datastarJSString(selector))
}

func (a DatastarAction) Retry(retry string) DatastarAction {
	return a.with("retry: " + datastarJSString(retry))
}

func (a DatastarAction) RequestCancellation(requestCancellation string) DatastarAction {
	return a.with("requestCancellation: " + datastarJSString(requestCancellation))
}

func (a DatastarAction) RetryInterval(milliseconds int) DatastarAction {
	return a.with("retryInterval: " + strconv.Itoa(milliseconds))
}

func (a DatastarAction) RetryScaler(scaler float64) DatastarAction {
	return a.with("retryScaler: " + strconv.FormatFloat(scaler, 'g', -1, 64))
}

func (a DatastarAction) RetryMaxWait(milliseconds int) DatastarAction {
	return a.with("retryMaxWait: " + strconv.Itoa(milliseconds))
}

func (a DatastarAction) RetryMaxCount(count int) DatastarAction {
	return a.with("retryMaxCount: " + strconv.Itoa(count))
}

func (a DatastarAction) String() string {
	if len(a.options) == 0 {
		return a.verb + "('" + a.url + "')"
	}
	return a.verb + "('" + a.url + "', {" + strings.Join(a.options, ", ") + "})"
}

func (a DatastarAction) JS() template.JS {
	return template.JS(a.String())
}

func datastarJSString(s string) string {
	var b strings.Builder
	b.Grow(len(s) + 2)
	b.WriteByte('\'')
	for _, r := range s {
		switch r {
		case '\\':
			b.WriteString("\\\\")
		case '\'':
			b.WriteString("\\'")
		case '\n':
			b.WriteString("\\n")
		default:
			b.WriteRune(r)
		}
	}
	b.WriteByte('\'')
	return b.String()
}

type DatastarEventTemplateData[R, T any] struct {
	receiver                  R
	request                   *http.Request
	result                    T
	pathsPrefix               string
	selector, mode, namespace *string
	useViewTransition         *bool
	errList                   []error
	data                      *bytes.Buffer
}

func (m *DatastarEventTemplateData[R, T]) String() string {
	return ""
}

func (m *DatastarEventTemplateData[R, T]) Receiver() R {
	return m.receiver
}

func (m *DatastarEventTemplateData[R, T]) Request() *http.Request {
	return m.request
}

func (m *DatastarEventTemplateData[R, T]) Result() T {
	return m.result
}

func (m *DatastarEventTemplateData[R, T]) Err() error {
	return errors.Join(m.errList...)
}

func (m *DatastarEventTemplateData[R, T]) Selector(selector string) *DatastarEventTemplateData[R, T] {
	m.selector = &selector
	return m
}

func (m *DatastarEventTemplateData[R, T]) Mode(mode string) *DatastarEventTemplateData[R, T] {
	m.mode = &mode
	return m
}

func (m *DatastarEventTemplateData[R, T]) Namespace(namespace string) *DatastarEventTemplateData[R, T] {
	m.namespace = &namespace
	return m
}

func (m *DatastarEventTemplateData[R, T]) UseViewTransition(useViewTransition bool) *DatastarEventTemplateData[R, T] {
	m.useViewTransition = &useViewTransition
	return m
}

func (m *DatastarEventTemplateData[R, T]) Path() TemplateRoutePaths {
	return TemplateRoutePaths{pathsPrefix: m.pathsPrefix}
}

func (m *DatastarEventTemplateData[R, T]) WriteTo(w io.Writer) (int64, error) {
	var bytesWritten int
	if n, err := io.WriteString(w, "event: datastar-patch-elements\n"); err != nil {
		return int64(bytesWritten + n), err
	} else {
		bytesWritten += n
	}
	if m.selector != nil {
		if n, err := io.WriteString(w, "data: selector "); err != nil {
			return int64(bytesWritten + n), err
		} else {
			bytesWritten += n
		}
		if n, err := io.WriteString(w, *m.selector); err != nil {
			return int64(bytesWritten + n), err
		} else {
			bytesWritten += n
		}
		if n, err := w.Write([]byte{'\n'}); err != nil {
			return int64(bytesWritten + n), err
		} else {
			bytesWritten += n
		}
	}
	if m.mode != nil && *m.mode != "outer" {
		if n, err := io.WriteString(w, "data: mode "); err != nil {
			return int64(bytesWritten + n), err
		} else {
			bytesWritten += n
		}
		if n, err := io.WriteString(w, *m.mode); err != nil {
			return int64(bytesWritten + n), err
		} else {
			bytesWritten += n
		}
		if n, err := w.Write([]byte{'\n'}); err != nil {
			return int64(bytesWritten + n), err
		} else {
			bytesWritten += n
		}
	}
	if m.namespace != nil {
		if n, err := io.WriteString(w, "data: namespace "); err != nil {
			return int64(bytesWritten + n), err
		} else {
			bytesWritten += n
		}
		if n, err := io.WriteString(w, *m.namespace); err != nil {
			return int64(bytesWritten + n), err
		} else {
			bytesWritten += n
		}
		if n, err := w.Write([]byte{'\n'}); err != nil {
			return int64(bytesWritten + n), err
		} else {
			bytesWritten += n
		}
	}
	if m.useViewTransition != nil && *m.useViewTransition {
		if n, err := io.WriteString(w, "data: useViewTransition true\n"); err != nil {
			return int64(bytesWritten + n), err
		} else {
			bytesWritten += n
		}
	}
	data := m.data.Bytes()
	if bytes.IndexByte(data, '\r') >= 0 {
		data = bytes.ReplaceAll(data, []byte("\r\n"), []byte("\n"))
		data = bytes.ReplaceAll(data, []byte("\r"), []byte("\n"))
	}
	data = bytes.TrimSuffix(data, []byte{'\n'})
	for line := range bytes.SplitSeq(data, []byte{'\n'}) {
		if n, err := io.WriteString(w, "data: elements "); err != nil {
			return int64(bytesWritten + n), err
		} else {
			bytesWritten += n
		}
		if len(line) > 0 {
			if n, err := w.Write(line); err != nil {
				return int64(bytesWritten + n), err
			} else {
				bytesWritten += n
			}
		}
		if n, err := w.Write([]byte{'\n'}); err != nil {
			return int64(bytesWritten + n), err
		} else {
			bytesWritten += n
		}
	}
	if n, err := w.Write([]byte{'\n'}); err != nil {
		return int64(bytesWritten + n), err
	} else {
		bytesWritten += n
	}
	return int64(bytesWritten), nil
}

func datastarMarshalSignals(buf *bytes.Buffer, v any) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	_, err = buf.Write(b)
	return err
}

type TemplateRoutePaths struct {
	pathsPrefix string
}

func (routePaths TemplateRoutePaths) Index() string {
	return "/"
}

func (routePaths TemplateRoutePaths) Clock() string {
	return path.Join(cmp.Or(routePaths.pathsPrefix, "/"), "clock")
}

func (routePaths TemplateRoutePaths) Hello() string {
	return path.Join(cmp.Or(routePaths.pathsPrefix, "/"), "hello.js")
}

func (routePaths TemplateRoutePaths) Increment() string {
	return path.Join(cmp.Or(routePaths.pathsPrefix, "/"), "increment")
}
