// Code generated by muxt generate --use-receiver-type=Server --output-datastar. DO NOT EDIT.
// muxt version: (devel)

package main

import (
	"bytes"
	"cmp"
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"log/slog"
	"net/http"
	"path"
	"strconv"
	"strings"
	"sync"
)

type RoutesReceiver interface {
	Index(_ context.Context) (SearchResults, error)
	ProverbsAPI(_ context.Context, form APIForm) (SearchResults, error)
	SearchProverbs(_ context.Context, signals SearchSignals, sseResults func(SearchResults) error)
}

func TemplateRoutes(mux *http.ServeMux, receiver RoutesReceiver) TemplateRoutePaths {
	pathsPrefix := ""
	bytesBufferPool := sync.Pool{New: func() any {
		return bytes.NewBuffer(nil)
	}}
	mux.HandleFunc("GET /", func(response http.ResponseWriter, request *http.Request) {
		var td = TemplateData[RoutesReceiver, SearchResults]{receiver: receiver, response: response, request: request, pathsPrefix: pathsPrefix}
		ctx := request.Context()
		buf := bytesBufferPool.Get().(*bytes.Buffer)
		buf.Reset()
		defer bytesBufferPool.Put(buf)
		if len(td.errList) == 0 {
			var err error
			td.result, err = receiver.Index(ctx)
			if err != nil {
				td.errList = append(td.errList, err)
				td.errStatusCode = http.StatusInternalServerError
			}
		}
		if err := templates.ExecuteTemplate(buf, "GET / Index(ctx)", &td); err != nil {
			slog.ErrorContext(request.Context(), "failed to render page", slog.String("path", request.URL.Path), slog.String("pattern", request.Pattern), slog.String("error", err.Error()))
			http.Error(response, "failed to render page", http.StatusInternalServerError)
			return
		}
		defaultStatusCode := http.StatusOK
		if buf.Len() == 0 {
			defaultStatusCode = http.StatusNoContent
		}
		statusCode := cmp.Or(td.statusCode, td.errStatusCode, defaultStatusCode)
		if td.redirectURL != "" {
			http.Redirect(response, request, td.redirectURL, statusCode)
			return
		}
		if contentType := response.Header().Get("content-type"); contentType == "" {
			response.Header().Set("content-type", "text/html; charset=utf-8")
		}
		response.Header().Set("content-length", strconv.Itoa(buf.Len()))
		response.WriteHeader(statusCode)
		_, _ = buf.WriteTo(response)
	})
	mux.HandleFunc("GET /api/proverbs", func(response http.ResponseWriter, request *http.Request) {
		var td = TemplateData[RoutesReceiver, SearchResults]{receiver: receiver, response: response, request: request, pathsPrefix: pathsPrefix}
		ctx := request.Context()
		if err := request.ParseForm(); err != nil {
			http.Error(response, err.Error(), http.StatusBadRequest)
			return
		}
		var form APIForm
		form.Query = request.FormValue("query")
		buf := bytesBufferPool.Get().(*bytes.Buffer)
		buf.Reset()
		defer bytesBufferPool.Put(buf)
		if len(td.errList) == 0 {
			var err error
			td.result, err = receiver.ProverbsAPI(ctx, form)
			if err != nil {
				td.errList = append(td.errList, err)
				td.errStatusCode = http.StatusInternalServerError
			}
		}
		if err := templates.ExecuteTemplate(buf, "GET /api/proverbs marshalJSON(ProverbsAPI(ctx, form))", &td); err != nil {
			slog.ErrorContext(request.Context(), "failed to render page", slog.String("path", request.URL.Path), slog.String("pattern", request.Pattern), slog.String("error", err.Error()))
			http.Error(response, "failed to render page", http.StatusInternalServerError)
			return
		}
		if len(td.errList) == 0 {
			buf.Reset()
			jsonBody, err := json.Marshal(td.result)
			if err != nil {
				http.Error(response, http.StatusText(http.StatusInternalServerError), http.StatusInternalServerError)
				return
			}
			_, _ = buf.Write(jsonBody)
			response.Header().Set("content-type", "application/json")
		}
		defaultStatusCode := http.StatusOK
		if buf.Len() == 0 {
			defaultStatusCode = http.StatusNoContent
		}
		statusCode := cmp.Or(td.statusCode, td.errStatusCode, defaultStatusCode)
		if contentType := response.Header().Get("content-type"); contentType == "" {
			response.Header().Set("content-type", "text/html; charset=utf-8")
		}
		response.Header().Set("content-length", strconv.Itoa(buf.Len()))
		response.WriteHeader(statusCode)
		_, _ = buf.WriteTo(response)
	})
	mux.HandleFunc("POST /search", func(response http.ResponseWriter, request *http.Request) {
		defer func() {
			_ = request.Body.Close()
		}()
		flusher, ok := response.(http.Flusher)
		if !ok {
			http.Error(response, "streaming unsupported", http.StatusInternalServerError)
			return
		}
		ctx := request.Context()
		var bodyValue SearchSignals
		if err := json.NewDecoder(request.Body).Decode(&bodyValue); err != nil {
			http.Error(response, err.Error(), http.StatusBadRequest)
			return
		}
		h := response.Header()
		h.Set("Content-Type", "text/event-stream")
		h.Set("Connection", "keep-alive")
		h.Set("Cache-Control", "no-store")
		response.WriteHeader(http.StatusOK)
		flusher.Flush()
		var mut sync.Mutex
		receiver.SearchProverbs(ctx, bodyValue, func(result SearchResults) error {
			if err := request.Context().Err(); err != nil {
				return err
			}
			buf := bytesBufferPool.Get().(*bytes.Buffer)
			buf.Reset()
			defer bytesBufferPool.Put(buf)
			td := SSETemplateData[RoutesReceiver, SearchResults]{receiver: receiver, request: request, pathsPrefix: pathsPrefix, result: result}
			if err := templates.ExecuteTemplate(buf, "sseResults", &td); err != nil {
				slog.ErrorContext(request.Context(), "failed to render page", slog.String("path", request.URL.Path), slog.String("pattern", request.Pattern), slog.String("error", err.Error()))
				return err
			}
			td.data = buf
			mut.Lock()
			defer mut.Unlock()
			if _, err := td.WriteTo(response); err != nil {
				return err
			}
			flusher.Flush()
			return nil
		})
	})
	return TemplateRoutePaths{pathsPrefix: pathsPrefix}
}

type TemplateData[R any, T any] struct {
	receiver      R
	response      http.ResponseWriter
	request       *http.Request
	result        T
	statusCode    int
	errStatusCode int
	okay          bool
	errList       []error
	redirectURL   string
	pathsPrefix   string
}

func (data *TemplateData[R, T]) MuxtVersion() string {
	const muxtVersion = "(devel)"
	return muxtVersion
}

func (data *TemplateData[R, T]) Path() TemplateRoutePaths {
	return TemplateRoutePaths{pathsPrefix: data.pathsPrefix}
}

func (data *TemplateData[R, T]) Result() T {
	return data.result
}

func (data *TemplateData[R, T]) Request() *http.Request {
	return data.request
}

func (data *TemplateData[R, T]) StatusCode(statusCode int) *TemplateData[R, T] {
	data.statusCode = statusCode
	return data
}

func (data *TemplateData[R, T]) Header(key, value string) *TemplateData[R, T] {
	data.response.Header().Set(key, value)
	return data
}

func (data *TemplateData[R, T]) Ok() bool {
	return data.okay
}

func (data *TemplateData[R, T]) Err() error {
	return errors.Join(data.errList...)
}

func (data *TemplateData[R, T]) Receiver() R {
	return data.receiver
}

func (data *TemplateData[R, T]) Redirect(url string, code int) (*TemplateData[R, T], error) {
	if code < 300 || code >= 400 {
		return data, fmt.Errorf("invalid status code %d for redirect", code)
	}
	data.redirectURL = url
	return data.StatusCode(code), nil
}

func (data *TemplateData[R, T]) RedirectMultipleChoices(url string) (*TemplateData[R, T], error) {
	return data.Redirect(url, http.StatusMultipleChoices)
}

func (data *TemplateData[R, T]) RedirectMovedPermanently(url string) (*TemplateData[R, T], error) {
	return data.Redirect(url, http.StatusMovedPermanently)
}

func (data *TemplateData[R, T]) RedirectFound(url string) (*TemplateData[R, T], error) {
	return data.Redirect(url, http.StatusFound)
}

func (data *TemplateData[R, T]) RedirectSeeOther(url string) (*TemplateData[R, T], error) {
	return data.Redirect(url, http.StatusSeeOther)
}

func (data *TemplateData[R, T]) String() string {
	return ""
}

type SSETemplateData[R, T any] struct {
	receiver          R
	request           *http.Request
	result            T
	pathsPrefix       string
	event, id         *string
	retryMilliseconds *int
	errList           []error
	data              *bytes.Buffer
	selector, mode    *string
	useViewTransition bool
}

func (m *SSETemplateData[R, T]) String() string {
	return ""
}

func (m *SSETemplateData[R, T]) Receiver() R {
	return m.receiver
}

func (m *SSETemplateData[R, T]) Request() *http.Request {
	return m.request
}

func (m *SSETemplateData[R, T]) Result() T {
	return m.result
}

func (m *SSETemplateData[R, T]) Err() error {
	return errors.Join(m.errList...)
}

func (m *SSETemplateData[R, T]) ID(id string) *SSETemplateData[R, T] {
	m.id = &id
	return m
}

func (m *SSETemplateData[R, T]) Retry(retryMilliseconds int) *SSETemplateData[R, T] {
	m.retryMilliseconds = &retryMilliseconds
	return m
}

func (m *SSETemplateData[R, T]) Path() TemplateRoutePaths {
	return TemplateRoutePaths{pathsPrefix: m.pathsPrefix}
}

func (m *SSETemplateData[R, T]) Selector(selector string) *SSETemplateData[R, T] {
	m.selector = &selector
	return m
}

func (m *SSETemplateData[R, T]) Mode(mode string) *SSETemplateData[R, T] {
	m.mode = &mode
	return m
}

func (m *SSETemplateData[R, T]) UseViewTransition(value bool) *SSETemplateData[R, T] {
	m.useViewTransition = value
	return m
}

func (m *SSETemplateData[R, T]) WriteTo(w io.Writer) (int64, error) {
	if m.id != nil && strings.ContainsAny(*m.id, "\r\n\x00") {
		return 0, errors.New("sse: id contains a forbidden character")
	}
	if m.selector != nil && strings.ContainsAny(*m.selector, "\r\n") {
		return 0, errors.New("sse: selector contains a forbidden character")
	}
	if m.mode != nil && strings.ContainsAny(*m.mode, "\r\n") {
		return 0, errors.New("sse: mode contains a forbidden character")
	}
	var bytesWritten int
	if n, err := io.WriteString(w, "event: datastar-patch-elements\n"); err != nil {
		return int64(bytesWritten + n), err
	} else {
		bytesWritten += n
	}
	if m.id != nil {
		if n, err := io.WriteString(w, "id: "); err != nil {
			return int64(bytesWritten + n), err
		} else {
			bytesWritten += n
		}
		if n, err := io.WriteString(w, *m.id); err != nil {
			return int64(bytesWritten + n), err
		} else {
			bytesWritten += n
		}
		if n, err := w.Write([]byte{'\n'}); err != nil {
			return int64(bytesWritten + n), err
		} else {
			bytesWritten += n
		}
	}
	if m.retryMilliseconds != nil {
		if n, err := io.WriteString(w, "retry: "); err != nil {
			return int64(bytesWritten + n), err
		} else {
			bytesWritten += n
		}
		var retryBuf [20]byte
		if n, err := w.Write(strconv.AppendInt(retryBuf[:0], int64(*m.retryMilliseconds), 10)); err != nil {
			return int64(bytesWritten + n), err
		} else {
			bytesWritten += n
		}
		if n, err := w.Write([]byte{'\n'}); err != nil {
			return int64(bytesWritten + n), err
		} else {
			bytesWritten += n
		}
	}
	if m.selector != nil {
		if n, err := io.WriteString(w, "data: selector "); err != nil {
			return int64(bytesWritten + n), err
		} else {
			bytesWritten += n
		}
		if n, err := io.WriteString(w, *m.selector); err != nil {
			return int64(bytesWritten + n), err
		} else {
			bytesWritten += n
		}
		if n, err := w.Write([]byte{'\n'}); err != nil {
			return int64(bytesWritten + n), err
		} else {
			bytesWritten += n
		}
	}
	if m.mode != nil {
		if n, err := io.WriteString(w, "data: mode "); err != nil {
			return int64(bytesWritten + n), err
		} else {
			bytesWritten += n
		}
		if n, err := io.WriteString(w, *m.mode); err != nil {
			return int64(bytesWritten + n), err
		} else {
			bytesWritten += n
		}
		if n, err := w.Write([]byte{'\n'}); err != nil {
			return int64(bytesWritten + n), err
		} else {
			bytesWritten += n
		}
	}
	if m.useViewTransition {
		if n, err := io.WriteString(w, "data: useViewTransition true\n"); err != nil {
			return int64(bytesWritten + n), err
		} else {
			bytesWritten += n
		}
	}
	data := m.data.Bytes()
	if bytes.IndexByte(data, '\r') >= 0 {
		data = bytes.ReplaceAll(data, []byte("\r\n"), []byte("\n"))
		data = bytes.ReplaceAll(data, []byte("\r"), []byte("\n"))
	}
	data = bytes.TrimSuffix(data, []byte{'\n'})
	for line := range bytes.SplitSeq(data, []byte{'\n'}) {
		if n, err := io.WriteString(w, "data: elements "); err != nil {
			return int64(bytesWritten + n), err
		} else {
			bytesWritten += n
		}
		if n, err := w.Write(line); err != nil {
			return int64(bytesWritten + n), err
		} else {
			bytesWritten += n
		}
		if n, err := w.Write([]byte{'\n'}); err != nil {
			return int64(bytesWritten + n), err
		} else {
			bytesWritten += n
		}
	}
	if n, err := w.Write([]byte{'\n'}); err != nil {
		return int64(bytesWritten + n), err
	} else {
		bytesWritten += n
	}
	return int64(bytesWritten), nil
}

type TemplateRoutePaths struct {
	pathsPrefix string
}

func (routePaths TemplateRoutePaths) Index() string {
	return "/"
}

func (routePaths TemplateRoutePaths) ProverbsAPI() string {
	return path.Join(cmp.Or(routePaths.pathsPrefix, "/"), "api/proverbs")
}

func (routePaths TemplateRoutePaths) SearchProverbs() string {
	return path.Join(cmp.Or(routePaths.pathsPrefix, "/"), "search")
}
