// Code generated by muxt generate --use-receiver-type=Server --use-htmx. DO NOT EDIT.
// muxt version: (devel)

package main

import (
	"bytes"
	"cmp"
	"errors"
	"fmt"
	"log/slog"
	"net/http"
	"path"
	"strconv"
	"sync"
)

type RoutesReceiver interface {
	Count() int64
	Decrement() int64
	Increment() int64
}

func TemplateRoutes(mux *http.ServeMux, receiver RoutesReceiver) TemplateRoutePaths {
	pathsPrefix := ""
	bytesBufferPool := sync.Pool{New: func() any {
		return bytes.NewBuffer(nil)
	}}
	mux.HandleFunc("/", func(response http.ResponseWriter, request *http.Request) {
		var td = HTMXTemplateData[RoutesReceiver, int64]{receiver: receiver, response: response, request: request, pathsPrefix: pathsPrefix}
		buf := bytesBufferPool.Get().(*bytes.Buffer)
		buf.Reset()
		defer bytesBufferPool.Put(buf)
		if len(td.errList) == 0 {
			td.result = receiver.Count()
			td.okay = true
		}
		if err := templates.ExecuteTemplate(buf, "/ Count()", &td); err != nil {
			slog.ErrorContext(request.Context(), "failed to render page", slog.String("path", request.URL.Path), slog.String("pattern", request.Pattern), slog.String("error", err.Error()))
			http.Error(response, "failed to render page", http.StatusInternalServerError)
			return
		}
		defaultStatusCode := http.StatusOK
		if buf.Len() == 0 {
			defaultStatusCode = http.StatusNoContent
		}
		statusCode := cmp.Or(td.statusCode, td.errStatusCode, defaultStatusCode)
		if contentType := response.Header().Get("content-type"); contentType == "" {
			response.Header().Set("content-type", "text/html; charset=utf-8")
		}
		response.Header().Set("content-length", strconv.Itoa(buf.Len()))
		response.WriteHeader(statusCode)
		_, _ = buf.WriteTo(response)
	})
	mux.HandleFunc("POST /count", func(response http.ResponseWriter, request *http.Request) {
		var td = HTMXTemplateData[RoutesReceiver, struct {
		}]{receiver: receiver, response: response, request: request, pathsPrefix: pathsPrefix}
		buf := bytesBufferPool.Get().(*bytes.Buffer)
		buf.Reset()
		defer bytesBufferPool.Put(buf)
		if err := templates.ExecuteTemplate(buf, "POST /count", &td); err != nil {
			slog.ErrorContext(request.Context(), "failed to render page", slog.String("path", request.URL.Path), slog.String("pattern", request.Pattern), slog.String("error", err.Error()))
			http.Error(response, "failed to render page", http.StatusInternalServerError)
			return
		}
		defaultStatusCode := http.StatusOK
		if buf.Len() == 0 {
			defaultStatusCode = http.StatusNoContent
		}
		statusCode := cmp.Or(td.statusCode, td.errStatusCode, defaultStatusCode)
		if td.redirectURL != "" {
			http.Redirect(response, request, td.redirectURL, statusCode)
			return
		}
		if contentType := response.Header().Get("content-type"); contentType == "" {
			response.Header().Set("content-type", "text/html; charset=utf-8")
		}
		response.Header().Set("content-length", strconv.Itoa(buf.Len()))
		response.WriteHeader(statusCode)
		_, _ = buf.WriteTo(response)
	})
	mux.HandleFunc("/decrement-count", func(response http.ResponseWriter, request *http.Request) {
		var td = HTMXTemplateData[RoutesReceiver, int64]{receiver: receiver, response: response, request: request, pathsPrefix: pathsPrefix}
		buf := bytesBufferPool.Get().(*bytes.Buffer)
		buf.Reset()
		defer bytesBufferPool.Put(buf)
		if len(td.errList) == 0 {
			td.result = receiver.Decrement()
			td.okay = true
		}
		if err := templates.ExecuteTemplate(buf, "/decrement-count Decrement()", &td); err != nil {
			slog.ErrorContext(request.Context(), "failed to render page", slog.String("path", request.URL.Path), slog.String("pattern", request.Pattern), slog.String("error", err.Error()))
			http.Error(response, "failed to render page", http.StatusInternalServerError)
			return
		}
		defaultStatusCode := http.StatusOK
		if buf.Len() == 0 {
			defaultStatusCode = http.StatusNoContent
		}
		statusCode := cmp.Or(td.statusCode, td.errStatusCode, defaultStatusCode)
		if td.redirectURL != "" {
			http.Redirect(response, request, td.redirectURL, statusCode)
			return
		}
		if contentType := response.Header().Get("content-type"); contentType == "" {
			response.Header().Set("content-type", "text/html; charset=utf-8")
		}
		response.Header().Set("content-length", strconv.Itoa(buf.Len()))
		response.WriteHeader(statusCode)
		_, _ = buf.WriteTo(response)
	})
	mux.HandleFunc("/increment-count", func(response http.ResponseWriter, request *http.Request) {
		var td = HTMXTemplateData[RoutesReceiver, int64]{receiver: receiver, response: response, request: request, pathsPrefix: pathsPrefix}
		buf := bytesBufferPool.Get().(*bytes.Buffer)
		buf.Reset()
		defer bytesBufferPool.Put(buf)
		if len(td.errList) == 0 {
			td.result = receiver.Increment()
			td.okay = true
		}
		if err := templates.ExecuteTemplate(buf, "/increment-count Increment()", &td); err != nil {
			slog.ErrorContext(request.Context(), "failed to render page", slog.String("path", request.URL.Path), slog.String("pattern", request.Pattern), slog.String("error", err.Error()))
			http.Error(response, "failed to render page", http.StatusInternalServerError)
			return
		}
		defaultStatusCode := http.StatusOK
		if buf.Len() == 0 {
			defaultStatusCode = http.StatusNoContent
		}
		statusCode := cmp.Or(td.statusCode, td.errStatusCode, defaultStatusCode)
		if td.redirectURL != "" {
			http.Redirect(response, request, td.redirectURL, statusCode)
			return
		}
		if contentType := response.Header().Get("content-type"); contentType == "" {
			response.Header().Set("content-type", "text/html; charset=utf-8")
		}
		response.Header().Set("content-length", strconv.Itoa(buf.Len()))
		response.WriteHeader(statusCode)
		_, _ = buf.WriteTo(response)
	})
	return TemplateRoutePaths{pathsPrefix: pathsPrefix}
}

type HTMXTemplateData[R any, T any] struct {
	receiver      R
	response      http.ResponseWriter
	request       *http.Request
	result        T
	statusCode    int
	errStatusCode int
	okay          bool
	errList       []error
	redirectURL   string
	pathsPrefix   string
}

func (data *HTMXTemplateData[R, T]) MuxtVersion() string {
	const muxtVersion = "(devel)"
	return muxtVersion
}

func (data *HTMXTemplateData[R, T]) Path() TemplateRoutePaths {
	return TemplateRoutePaths{pathsPrefix: data.pathsPrefix}
}

func (data *HTMXTemplateData[R, T]) Result() T {
	return data.result
}

func (data *HTMXTemplateData[R, T]) Request() *http.Request {
	return data.request
}

func (data *HTMXTemplateData[R, T]) StatusCode(statusCode int) *HTMXTemplateData[R, T] {
	data.statusCode = statusCode
	return data
}

func (data *HTMXTemplateData[R, T]) Header(key, value string) *HTMXTemplateData[R, T] {
	data.response.Header().Set(key, value)
	return data
}

func (data *HTMXTemplateData[R, T]) Ok() bool {
	return data.okay
}

func (data *HTMXTemplateData[R, T]) Err() error {
	return errors.Join(data.errList...)
}

func (data *HTMXTemplateData[R, T]) Receiver() R {
	return data.receiver
}

func (data *HTMXTemplateData[R, T]) Redirect(url string, code int) (*HTMXTemplateData[R, T], error) {
	if code < 300 || code >= 400 {
		return data, fmt.Errorf("invalid status code %d for redirect", code)
	}
	data.redirectURL = url
	return data.StatusCode(code), nil
}

func (data *HTMXTemplateData[R, T]) RedirectMultipleChoices(url string) (*HTMXTemplateData[R, T], error) {
	return data.Redirect(url, http.StatusMultipleChoices)
}

func (data *HTMXTemplateData[R, T]) RedirectMovedPermanently(url string) (*HTMXTemplateData[R, T], error) {
	return data.Redirect(url, http.StatusMovedPermanently)
}

func (data *HTMXTemplateData[R, T]) RedirectFound(url string) (*HTMXTemplateData[R, T], error) {
	return data.Redirect(url, http.StatusFound)
}

func (data *HTMXTemplateData[R, T]) RedirectSeeOther(url string) (*HTMXTemplateData[R, T], error) {
	return data.Redirect(url, http.StatusSeeOther)
}

func (data *HTMXTemplateData[R, T]) String() string {
	return ""
}

func (data *HTMXTemplateData[R, T]) HXLocation(link string) *HTMXTemplateData[R, T] {
	return data.Header("HX-Location", link)
}

func (data *HTMXTemplateData[R, T]) HXPushURL(link string) *HTMXTemplateData[R, T] {
	return data.Header("HX-Push-Url", link)
}

func (data *HTMXTemplateData[R, T]) HXRedirect(link string) *HTMXTemplateData[R, T] {
	return data.Header("HX-Redirect", link)
}

func (data *HTMXTemplateData[R, T]) HXRefresh() *HTMXTemplateData[R, T] {
	return data.Header("HX-Refresh", "true")
}

func (data *HTMXTemplateData[R, T]) HXReplaceURL(link string) *HTMXTemplateData[R, T] {
	return data.Header("HX-Replace-Url", link)
}

func (data *HTMXTemplateData[R, T]) HXReswap(swap string) *HTMXTemplateData[R, T] {
	return data.Header("HX-Reswap", swap)
}

func (data *HTMXTemplateData[R, T]) HXRetarget(target string) *HTMXTemplateData[R, T] {
	return data.Header("HX-Retarget", target)
}

func (data *HTMXTemplateData[R, T]) HXReselect(selector string) *HTMXTemplateData[R, T] {
	return data.Header("HX-Reselect", selector)
}

func (data *HTMXTemplateData[R, T]) HXTrigger(eventName string) *HTMXTemplateData[R, T] {
	return data.Header("HX-Trigger", eventName)
}

func (data *HTMXTemplateData[R, T]) HXTriggerAfterSettle(eventName string) *HTMXTemplateData[R, T] {
	return data.Header("HX-Trigger-After-Settle", eventName)
}

func (data *HTMXTemplateData[R, T]) HXTriggerAfterSwap(eventName string) *HTMXTemplateData[R, T] {
	return data.Header("HX-Trigger-After-Swap", eventName)
}

func (data *HTMXTemplateData[R, T]) HXBoosted() bool {
	return data.Request().Header.Get("HX-Boosted") != ""
}

func (data *HTMXTemplateData[R, T]) HXCurrentURL() string {
	return data.Request().Header.Get("HX-Current-Url")
}

func (data *HTMXTemplateData[R, T]) HXHistoryRestoreRequest() bool {
	return data.Request().Header.Get("HX-History-Restore-Request") == "true"
}

func (data *HTMXTemplateData[R, T]) HXPrompt() string {
	return data.Request().Header.Get("HX-Prompt")
}

func (data *HTMXTemplateData[R, T]) HXRequest() bool {
	return data.Request().Header.Get("HX-Request") == "true"
}

func (data *HTMXTemplateData[R, T]) HXTargetElementID() string {
	return data.Request().Header.Get("HX-Target")
}

func (data *HTMXTemplateData[R, T]) HXTriggerName() string {
	return data.Request().Header.Get("HX-Trigger-Name")
}

func (data *HTMXTemplateData[R, T]) HXTriggerElementID() string {
	return data.Request().Header.Get("HX-Trigger")
}

type TemplateRoutePaths struct {
	pathsPrefix string
}

func (routePaths TemplateRoutePaths) Count() string {
	return "/"
}

func (routePaths TemplateRoutePaths) CreateCount() string {
	return path.Join(cmp.Or(routePaths.pathsPrefix, "/"), "count")
}

func (routePaths TemplateRoutePaths) Decrement() string {
	return path.Join(cmp.Or(routePaths.pathsPrefix, "/"), "decrement-count")
}

func (routePaths TemplateRoutePaths) Increment() string {
	return path.Join(cmp.Or(routePaths.pathsPrefix, "/"), "increment-count")
}
