package generate

import (
	"os"
	"path/filepath"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func TestFileArguments(t *testing.T) {
	dir := t.TempDir()
	for name, content := range map[string]string{
		"template_routes.go":  "// Code generated by muxt generate --use-receiver-type=T. DO NOT EDIT.\n\npackage server\n",
		"index_gen.go":        "// Code generated by muxt generate . DO NOT EDIT.\n",
		"other_generated.go":  "// Code generated by stringer. DO NOT EDIT.\n",
		"handwritten.go":      "package server\n",
		"notes.txt":           "// Code generated by muxt generate --output-file=notes.txt. DO NOT EDIT.\n",
		"second_line.go":      "package server\n// Code generated by muxt generate --output-htmx. DO NOT EDIT.\n",
		"empty.go":            "",
		"sub/template_rou.go": "// Code generated by muxt generate --output-htmx. DO NOT EDIT.\n",
	} {
		path := filepath.Join(dir, filepath.FromSlash(name))
		require.NoError(t, os.MkdirAll(filepath.Dir(path), 0o755))
		require.NoError(t, os.WriteFile(path, []byte(content), 0o644))
	}

	files, err := FileArguments(dir, DefaultRoutesFunctionName)
	require.NoError(t, err)
	assert.Equal(t, map[string][]string{
		filepath.Join(dir, "template_routes.go"): {"--use-receiver-type=T"},
		filepath.Join(dir, "index_gen.go"):       {},
	}, files, "only the .go files in the directory itself whose first line is the muxt header")

	_, err = FileArguments(filepath.Join(dir, "missing"), DefaultRoutesFunctionName)
	assert.Error(t, err)
}
