package generate

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// FileArguments scans the working directory for muxt-generated Go files.
//
// Files are identified by:
// 1. Having a "// Code generated by muxt generate" comment on the first line
// 2. Matching the routes function name extracted from the generation comment
//
// Returns a map of absolute file paths and the muxt arguments passed to generate them.
func FileArguments(workingDirectory, routesFunction string) (map[string][]string, error) {
	generatedFiles := make(map[string][]string)

	entries, err := os.ReadDir(workingDirectory)
	if err != nil {
		return nil, err
	}

	for _, entry := range entries {
		if entry.IsDir() || !strings.HasSuffix(entry.Name(), ".go") {
			continue
		}

		filePath := filepath.Join(workingDirectory, entry.Name())
		content, err := os.ReadFile(filePath)
		if err != nil {
			return nil, fmt.Errorf("failed to read %s: %w", filePath, err)
		}

		// Check if file has muxt generation comment
		lines := strings.Split(string(content), "\n")
		if len(lines) == 0 {
			continue
		}

		firstLine := lines[0]

		prefix := "// Code generated by muxt generate "
		suffix := ". DO NOT EDIT."

		if !strings.HasPrefix(firstLine, prefix) || !strings.HasSuffix(firstLine, suffix) {
			continue
		}
		command := strings.TrimPrefix(firstLine, prefix)
		command = strings.TrimSuffix(command, suffix)

		generatedFiles[filePath] = strings.Fields(command)
	}

	return generatedFiles, nil
}
