package generate_test

import "github.com/typelate/muxt/internal/generate"

// snapshots names the configuration each archive in testdata is generated
// with: the configuration the command line in the comment parses into.
//
// TestCommandLineConfigurations in internal/cli states what command lines
// parse into, with literals like these. Search for a literal to find its
// twin. They need not match field for field, but every configuration here
// is one a command line can produce: rejecting a configuration that cannot
// work is the command line's job, so nothing here tests one.
type snapshotCase struct {
	archive string
	config  generate.RoutesFileConfiguration
}

var snapshots = []snapshotCase{
	{
		// muxt generate
		archive: "err_duplicate_pattern",
		config: generate.RoutesFileConfiguration{
			MuxtVersion:                      "v1.2.3",
			PackageName:                      "main",
			RoutesFunction:                   "TemplateRoutes",
			ReceiverInterface:                "RoutesReceiver",
			TemplateDataType:                 "TemplateData",
			SSETemplateDataType:              "SSETemplateData",
			TemplateRoutePathsTypeName:       "TemplateRoutePaths",
			TemplatesVariables:               []string{"templates"},
			OutputFileName:                   "template_routes.go",
			OutputExportedDefaultIdentifiers: true,
			OutputMuxtVersion:                true,
		},
	},
	{
		// muxt generate
		archive: "err_name_errors",
		config: generate.RoutesFileConfiguration{
			MuxtVersion:                      "v1.2.3",
			PackageName:                      "main",
			RoutesFunction:                   "TemplateRoutes",
			ReceiverInterface:                "RoutesReceiver",
			TemplateDataType:                 "TemplateData",
			SSETemplateDataType:              "SSETemplateData",
			TemplateRoutePathsTypeName:       "TemplateRoutePaths",
			TemplatesVariables:               []string{"templates"},
			OutputFileName:                   "template_routes.go",
			OutputExportedDefaultIdentifiers: true,
			OutputMuxtVersion:                true,
		},
	},
	{
		// muxt generate --use-receiver-type=T
		archive: "err_resolution",
		config: generate.RoutesFileConfiguration{
			MuxtVersion:                      "v1.2.3",
			PackageName:                      "main",
			RoutesFunction:                   "TemplateRoutes",
			ReceiverType:                     "T",
			ReceiverInterface:                "RoutesReceiver",
			TemplateDataType:                 "TemplateData",
			SSETemplateDataType:              "SSETemplateData",
			TemplateRoutePathsTypeName:       "TemplateRoutePaths",
			TemplatesVariables:               []string{"templates"},
			OutputFileName:                   "template_routes.go",
			OutputExportedDefaultIdentifiers: true,
			OutputMuxtVersion:                true,
		},
	},
	{
		// muxt generate --use-receiver-type=T
		archive: "err_response_state_with_response_argument",
		config: generate.RoutesFileConfiguration{
			MuxtVersion:                      "v1.2.3",
			PackageName:                      "main",
			RoutesFunction:                   "TemplateRoutes",
			ReceiverType:                     "T",
			ReceiverInterface:                "RoutesReceiver",
			TemplateDataType:                 "TemplateData",
			SSETemplateDataType:              "SSETemplateData",
			TemplateRoutePathsTypeName:       "TemplateRoutePaths",
			TemplatesVariables:               []string{"templates"},
			OutputFileName:                   "template_routes.go",
			OutputExportedDefaultIdentifiers: true,
			OutputMuxtVersion:                true,
		},
	},
	{
		// muxt generate
		archive: "err_route_paths_method_collision",
		config: generate.RoutesFileConfiguration{
			MuxtVersion:                      "v1.2.3",
			PackageName:                      "main",
			RoutesFunction:                   "TemplateRoutes",
			ReceiverInterface:                "RoutesReceiver",
			TemplateDataType:                 "TemplateData",
			SSETemplateDataType:              "SSETemplateData",
			TemplateRoutePathsTypeName:       "TemplateRoutePaths",
			TemplatesVariables:               []string{"templates"},
			OutputFileName:                   "template_routes.go",
			OutputExportedDefaultIdentifiers: true,
			OutputMuxtVersion:                true,
		},
	},
	{
		// muxt generate
		archive: "err_signals_without_datastar",
		config: generate.RoutesFileConfiguration{
			MuxtVersion:                      "v1.2.3",
			PackageName:                      "main",
			RoutesFunction:                   "TemplateRoutes",
			ReceiverInterface:                "RoutesReceiver",
			TemplateDataType:                 "TemplateData",
			SSETemplateDataType:              "SSETemplateData",
			TemplateRoutePathsTypeName:       "TemplateRoutePaths",
			TemplatesVariables:               []string{"templates"},
			OutputFileName:                   "template_routes.go",
			OutputExportedDefaultIdentifiers: true,
			OutputMuxtVersion:                true,
		},
	},
	{
		// muxt generate --use-receiver-type=T
		archive: "execute_callback",
		config: generate.RoutesFileConfiguration{
			MuxtVersion:                      "v1.2.3",
			PackageName:                      "main",
			RoutesFunction:                   "TemplateRoutes",
			ReceiverType:                     "T",
			ReceiverInterface:                "RoutesReceiver",
			TemplateDataType:                 "TemplateData",
			SSETemplateDataType:              "SSETemplateData",
			TemplateRoutePathsTypeName:       "TemplateRoutePaths",
			TemplatesVariables:               []string{"templates"},
			OutputFileName:                   "template_routes.go",
			OutputExportedDefaultIdentifiers: true,
			OutputMuxtVersion:                true,
		},
	},
	{
		// muxt generate --use-receiver-type=Server --output-file=routes.go --output-routes-func=Routes --output-receiver-interface=Handlers --output-template-data-type=Data --output-template-route-paths-type=Paths
		archive: "flag_custom_names",
		config: generate.RoutesFileConfiguration{
			MuxtVersion:                      "v1.2.3",
			PackageName:                      "main",
			RoutesFunction:                   "Routes",
			ReceiverType:                     "Server",
			ReceiverInterface:                "Handlers",
			TemplateDataType:                 "Data",
			SSETemplateDataType:              "SSETemplateData",
			TemplateRoutePathsTypeName:       "Paths",
			TemplatesVariables:               []string{"templates"},
			OutputFileName:                   "routes.go",
			OutputExportedDefaultIdentifiers: true,
			OutputMuxtVersion:                true,
		},
	},
	{
		// muxt generate --output-htmx
		archive: "flag_htmx",
		config: generate.RoutesFileConfiguration{
			MuxtVersion:                      "v1.2.3",
			PackageName:                      "main",
			RoutesFunction:                   "TemplateRoutes",
			ReceiverInterface:                "RoutesReceiver",
			TemplateDataType:                 "TemplateData",
			SSETemplateDataType:              "SSETemplateData",
			TemplateRoutePathsTypeName:       "TemplateRoutePaths",
			TemplatesVariables:               []string{"templates"},
			OutputFileName:                   "template_routes.go",
			OutputHTMX:                       true,
			OutputExportedDefaultIdentifiers: true,
			OutputMuxtVersion:                true,
		},
	},
	{
		// muxt generate --use-receiver-type=T --output-routes-func-with-logger-param --output-routes-func-with-path-prefix-param --output-routes-func-with-middleware-param
		archive: "flag_logger_path_prefix_middleware",
		config: generate.RoutesFileConfiguration{
			MuxtVersion:                      "v1.2.3",
			PackageName:                      "main",
			RoutesFunction:                   "TemplateRoutes",
			ReceiverType:                     "T",
			ReceiverInterface:                "RoutesReceiver",
			TemplateDataType:                 "TemplateData",
			SSETemplateDataType:              "SSETemplateData",
			TemplateRoutePathsTypeName:       "TemplateRoutePaths",
			TemplatesVariables:               []string{"templates"},
			OutputFileName:                   "template_routes.go",
			PathPrefix:                       true,
			Logger:                           true,
			Middleware:                       true,
			OutputExportedDefaultIdentifiers: true,
			OutputMuxtVersion:                true,
		},
	},
	{
		// muxt generate --use-receiver-type=T --output-multiple-files --output-routes-func-with-middleware-param
		archive: "flag_multiple_files",
		config: generate.RoutesFileConfiguration{
			MuxtVersion:                      "v1.2.3",
			PackageName:                      "main",
			RoutesFunction:                   "TemplateRoutes",
			ReceiverType:                     "T",
			ReceiverInterface:                "RoutesReceiver",
			TemplateDataType:                 "TemplateData",
			SSETemplateDataType:              "SSETemplateData",
			TemplateRoutePathsTypeName:       "TemplateRoutePaths",
			TemplatesVariables:               []string{"templates"},
			OutputFileName:                   "template_routes.go",
			Middleware:                       true,
			OutputMultipleFiles:              true,
			OutputExportedDefaultIdentifiers: true,
			OutputMuxtVersion:                true,
		},
	},
	{
		// muxt generate --output-exported-default-identifiers=false
		archive: "flag_unexported_identifiers",
		config: generate.RoutesFileConfiguration{
			MuxtVersion:                "v1.2.3",
			PackageName:                "main",
			RoutesFunction:             "templateRoutes",
			ReceiverInterface:          "routesReceiver",
			TemplateDataType:           "templateData",
			SSETemplateDataType:        "sseTemplateData",
			TemplateRoutePathsTypeName: "templateRoutePaths",
			TemplatesVariables:         []string{"templates"},
			OutputFileName:             "template_routes.go",
			OutputMuxtVersion:          true,
		},
	},
	{
		// muxt generate --output-muxt-version=false
		archive: "flag_without_muxt_version",
		config: generate.RoutesFileConfiguration{
			PackageName:                      "main",
			RoutesFunction:                   "TemplateRoutes",
			ReceiverInterface:                "RoutesReceiver",
			TemplateDataType:                 "TemplateData",
			SSETemplateDataType:              "SSETemplateData",
			TemplateRoutePathsTypeName:       "TemplateRoutePaths",
			TemplatesVariables:               []string{"templates"},
			OutputFileName:                   "template_routes.go",
			OutputExportedDefaultIdentifiers: true,
		},
	},
	{
		// muxt generate --use-receiver-type=T
		archive: "form_struct",
		config: generate.RoutesFileConfiguration{
			MuxtVersion:                      "v1.2.3",
			PackageName:                      "main",
			RoutesFunction:                   "TemplateRoutes",
			ReceiverType:                     "T",
			ReceiverInterface:                "RoutesReceiver",
			TemplateDataType:                 "TemplateData",
			SSETemplateDataType:              "SSETemplateData",
			TemplateRoutePathsTypeName:       "TemplateRoutePaths",
			TemplatesVariables:               []string{"templates"},
			OutputFileName:                   "template_routes.go",
			OutputExportedDefaultIdentifiers: true,
			OutputMuxtVersion:                true,
		},
	},
	{
		// muxt generate --use-receiver-type=T
		archive: "form_values",
		config: generate.RoutesFileConfiguration{
			MuxtVersion:                      "v1.2.3",
			PackageName:                      "main",
			RoutesFunction:                   "TemplateRoutes",
			ReceiverType:                     "T",
			ReceiverInterface:                "RoutesReceiver",
			TemplateDataType:                 "TemplateData",
			SSETemplateDataType:              "SSETemplateData",
			TemplateRoutePathsTypeName:       "TemplateRoutePaths",
			TemplatesVariables:               []string{"templates"},
			OutputFileName:                   "template_routes.go",
			OutputExportedDefaultIdentifiers: true,
			OutputMuxtVersion:                true,
		},
	},
	{
		// muxt generate
		archive: "inferred_methods",
		config: generate.RoutesFileConfiguration{
			MuxtVersion:                      "v1.2.3",
			PackageName:                      "main",
			RoutesFunction:                   "TemplateRoutes",
			ReceiverInterface:                "RoutesReceiver",
			TemplateDataType:                 "TemplateData",
			SSETemplateDataType:              "SSETemplateData",
			TemplateRoutePathsTypeName:       "TemplateRoutePaths",
			TemplatesVariables:               []string{"templates"},
			OutputFileName:                   "template_routes.go",
			OutputExportedDefaultIdentifiers: true,
			OutputMuxtVersion:                true,
		},
	},
	{
		// muxt generate --use-receiver-type=T
		archive: "last_event_id",
		config: generate.RoutesFileConfiguration{
			MuxtVersion:                      "v1.2.3",
			PackageName:                      "main",
			RoutesFunction:                   "TemplateRoutes",
			ReceiverType:                     "T",
			ReceiverInterface:                "RoutesReceiver",
			TemplateDataType:                 "TemplateData",
			SSETemplateDataType:              "SSETemplateData",
			TemplateRoutePathsTypeName:       "TemplateRoutePaths",
			TemplatesVariables:               []string{"templates"},
			OutputFileName:                   "template_routes.go",
			OutputExportedDefaultIdentifiers: true,
			OutputMuxtVersion:                true,
		},
	},
	{
		// muxt generate --use-receiver-type=T
		archive: "marshal_json",
		config: generate.RoutesFileConfiguration{
			MuxtVersion:                      "v1.2.3",
			PackageName:                      "main",
			RoutesFunction:                   "TemplateRoutes",
			ReceiverType:                     "T",
			ReceiverInterface:                "RoutesReceiver",
			TemplateDataType:                 "TemplateData",
			SSETemplateDataType:              "SSETemplateData",
			TemplateRoutePathsTypeName:       "TemplateRoutePaths",
			TemplatesVariables:               []string{"templates"},
			OutputFileName:                   "template_routes.go",
			OutputExportedDefaultIdentifiers: true,
			OutputMuxtVersion:                true,
		},
	},
	{
		// muxt generate --use-receiver-type=T --output-multipart-max-memory=1MiB
		archive: "multipart",
		config: generate.RoutesFileConfiguration{
			MuxtVersion:                      "v1.2.3",
			PackageName:                      "main",
			RoutesFunction:                   "TemplateRoutes",
			ReceiverType:                     "T",
			ReceiverInterface:                "RoutesReceiver",
			TemplateDataType:                 "TemplateData",
			SSETemplateDataType:              "SSETemplateData",
			TemplateRoutePathsTypeName:       "TemplateRoutePaths",
			TemplatesVariables:               []string{"templates"},
			OutputFileName:                   "template_routes.go",
			OutputExportedDefaultIdentifiers: true,
			OutputMuxtVersion:                true,
			MultipartMaxMemory:               1 << 20,
		},
	},
	{
		// muxt generate --use-receiver-type=T
		archive: "nested_calls",
		config: generate.RoutesFileConfiguration{
			MuxtVersion:                      "v1.2.3",
			PackageName:                      "main",
			RoutesFunction:                   "TemplateRoutes",
			ReceiverType:                     "T",
			ReceiverInterface:                "RoutesReceiver",
			TemplateDataType:                 "TemplateData",
			SSETemplateDataType:              "SSETemplateData",
			TemplateRoutePathsTypeName:       "TemplateRoutePaths",
			TemplatesVariables:               []string{"templates"},
			OutputFileName:                   "template_routes.go",
			OutputExportedDefaultIdentifiers: true,
			OutputMuxtVersion:                true,
		},
	},
	{
		// muxt generate --use-receiver-type=T
		archive: "path_parameter_types",
		config: generate.RoutesFileConfiguration{
			MuxtVersion:                      "v1.2.3",
			PackageName:                      "main",
			RoutesFunction:                   "TemplateRoutes",
			ReceiverType:                     "T",
			ReceiverInterface:                "RoutesReceiver",
			TemplateDataType:                 "TemplateData",
			SSETemplateDataType:              "SSETemplateData",
			TemplateRoutePathsTypeName:       "TemplateRoutePaths",
			TemplatesVariables:               []string{"templates"},
			OutputFileName:                   "template_routes.go",
			OutputExportedDefaultIdentifiers: true,
			OutputMuxtVersion:                true,
		},
	},
	{
		// muxt generate --use-receiver-type=Server
		archive: "receiver_method_sets",
		config: generate.RoutesFileConfiguration{
			MuxtVersion:                      "v1.2.3",
			PackageName:                      "main",
			RoutesFunction:                   "TemplateRoutes",
			ReceiverType:                     "Server",
			ReceiverInterface:                "RoutesReceiver",
			TemplateDataType:                 "TemplateData",
			SSETemplateDataType:              "SSETemplateData",
			TemplateRoutePathsTypeName:       "TemplateRoutePaths",
			TemplatesVariables:               []string{"templates"},
			OutputFileName:                   "template_routes.go",
			OutputExportedDefaultIdentifiers: true,
			OutputMuxtVersion:                true,
		},
	},
	{
		// muxt generate --use-receiver-type=T
		archive: "redirect",
		config: generate.RoutesFileConfiguration{
			MuxtVersion:                      "v1.2.3",
			PackageName:                      "main",
			RoutesFunction:                   "TemplateRoutes",
			ReceiverType:                     "T",
			ReceiverInterface:                "RoutesReceiver",
			TemplateDataType:                 "TemplateData",
			SSETemplateDataType:              "SSETemplateData",
			TemplateRoutePathsTypeName:       "TemplateRoutePaths",
			TemplatesVariables:               []string{"templates"},
			OutputFileName:                   "template_routes.go",
			OutputExportedDefaultIdentifiers: true,
			OutputMuxtVersion:                true,
		},
	},
	{
		// muxt generate --use-receiver-type=T
		archive: "request_body",
		config: generate.RoutesFileConfiguration{
			MuxtVersion:                      "v1.2.3",
			PackageName:                      "main",
			RoutesFunction:                   "TemplateRoutes",
			ReceiverType:                     "T",
			ReceiverInterface:                "RoutesReceiver",
			TemplateDataType:                 "TemplateData",
			SSETemplateDataType:              "SSETemplateData",
			TemplateRoutePathsTypeName:       "TemplateRoutePaths",
			TemplatesVariables:               []string{"templates"},
			OutputFileName:                   "template_routes.go",
			OutputExportedDefaultIdentifiers: true,
			OutputMuxtVersion:                true,
		},
	},
	{
		// muxt generate --use-receiver-type=T
		archive: "response_argument",
		config: generate.RoutesFileConfiguration{
			MuxtVersion:                      "v1.2.3",
			PackageName:                      "main",
			RoutesFunction:                   "TemplateRoutes",
			ReceiverType:                     "T",
			ReceiverInterface:                "RoutesReceiver",
			TemplateDataType:                 "TemplateData",
			SSETemplateDataType:              "SSETemplateData",
			TemplateRoutePathsTypeName:       "TemplateRoutePaths",
			TemplatesVariables:               []string{"templates"},
			OutputFileName:                   "template_routes.go",
			OutputExportedDefaultIdentifiers: true,
			OutputMuxtVersion:                true,
		},
	},
	{
		// muxt generate --use-receiver-type=T
		archive: "result_shapes",
		config: generate.RoutesFileConfiguration{
			MuxtVersion:                      "v1.2.3",
			PackageName:                      "main",
			RoutesFunction:                   "TemplateRoutes",
			ReceiverType:                     "T",
			ReceiverInterface:                "RoutesReceiver",
			TemplateDataType:                 "TemplateData",
			SSETemplateDataType:              "SSETemplateData",
			TemplateRoutePathsTypeName:       "TemplateRoutePaths",
			TemplatesVariables:               []string{"templates"},
			OutputFileName:                   "template_routes.go",
			OutputExportedDefaultIdentifiers: true,
			OutputMuxtVersion:                true,
		},
	},
	{
		// muxt generate
		archive: "route_without_call",
		config: generate.RoutesFileConfiguration{
			MuxtVersion:                      "v1.2.3",
			PackageName:                      "main",
			RoutesFunction:                   "TemplateRoutes",
			ReceiverInterface:                "RoutesReceiver",
			TemplateDataType:                 "TemplateData",
			SSETemplateDataType:              "SSETemplateData",
			TemplateRoutePathsTypeName:       "TemplateRoutePaths",
			TemplatesVariables:               []string{"templates"},
			OutputFileName:                   "template_routes.go",
			OutputExportedDefaultIdentifiers: true,
			OutputMuxtVersion:                true,
		},
	},
	{
		// muxt generate --use-receiver-type=T --output-datastar
		archive: "sse_datastar",
		config: generate.RoutesFileConfiguration{
			MuxtVersion:                      "v1.2.3",
			PackageName:                      "main",
			RoutesFunction:                   "TemplateRoutes",
			ReceiverType:                     "T",
			ReceiverInterface:                "RoutesReceiver",
			TemplateDataType:                 "TemplateData",
			SSETemplateDataType:              "SSETemplateData",
			TemplateRoutePathsTypeName:       "TemplateRoutePaths",
			TemplatesVariables:               []string{"templates"},
			OutputFileName:                   "template_routes.go",
			OutputDatastar:                   true,
			OutputExportedDefaultIdentifiers: true,
			OutputMuxtVersion:                true,
		},
	},
	{
		// muxt generate --use-receiver-type=T
		archive: "sse_messages_without_datastar",
		config: generate.RoutesFileConfiguration{
			MuxtVersion:                      "v1.2.3",
			PackageName:                      "main",
			RoutesFunction:                   "TemplateRoutes",
			ReceiverType:                     "T",
			ReceiverInterface:                "RoutesReceiver",
			TemplateDataType:                 "TemplateData",
			SSETemplateDataType:              "SSETemplateData",
			TemplateRoutePathsTypeName:       "TemplateRoutePaths",
			TemplatesVariables:               []string{"templates"},
			OutputFileName:                   "template_routes.go",
			OutputExportedDefaultIdentifiers: true,
			OutputMuxtVersion:                true,
		},
	},
	{
		// muxt generate --use-receiver-type=T
		archive: "sse",
		config: generate.RoutesFileConfiguration{
			MuxtVersion:                      "v1.2.3",
			PackageName:                      "main",
			RoutesFunction:                   "TemplateRoutes",
			ReceiverType:                     "T",
			ReceiverInterface:                "RoutesReceiver",
			TemplateDataType:                 "TemplateData",
			SSETemplateDataType:              "SSETemplateData",
			TemplateRoutePathsTypeName:       "TemplateRoutePaths",
			TemplatesVariables:               []string{"templates"},
			OutputFileName:                   "template_routes.go",
			OutputExportedDefaultIdentifiers: true,
			OutputMuxtVersion:                true,
		},
	},
	{
		// muxt generate --use-receiver-type=T
		archive: "status_codes",
		config: generate.RoutesFileConfiguration{
			MuxtVersion:                      "v1.2.3",
			PackageName:                      "main",
			RoutesFunction:                   "TemplateRoutes",
			ReceiverType:                     "T",
			ReceiverInterface:                "RoutesReceiver",
			TemplateDataType:                 "TemplateData",
			SSETemplateDataType:              "SSETemplateData",
			TemplateRoutePathsTypeName:       "TemplateRoutePaths",
			TemplatesVariables:               []string{"templates"},
			OutputFileName:                   "template_routes.go",
			OutputExportedDefaultIdentifiers: true,
			OutputMuxtVersion:                true,
		},
	},
	{
		// muxt generate --use-receiver-type=T
		archive: "synthesized_method_note",
		config: generate.RoutesFileConfiguration{
			MuxtVersion:                      "v1.2.3",
			PackageName:                      "main",
			RoutesFunction:                   "TemplateRoutes",
			ReceiverType:                     "T",
			ReceiverInterface:                "RoutesReceiver",
			TemplateDataType:                 "TemplateData",
			SSETemplateDataType:              "SSETemplateData",
			TemplateRoutePathsTypeName:       "TemplateRoutePaths",
			TemplatesVariables:               []string{"templates"},
			OutputFileName:                   "template_routes.go",
			OutputExportedDefaultIdentifiers: true,
			OutputMuxtVersion:                true,
		},
	},
}
