package analysis

import (
	"os"
	"path/filepath"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func writeFiles(t *testing.T, dir string, files map[string]string) {
	t.Helper()
	for name, content := range files {
		path := filepath.Join(dir, filepath.FromSlash(name))
		require.NoError(t, os.MkdirAll(filepath.Dir(path), 0o755))
		require.NoError(t, os.WriteFile(path, []byte(content), 0o644))
	}
}

func TestScanGeneratedHeaders(t *testing.T) {
	dir := t.TempDir()
	writeFiles(t, dir, map[string]string{
		"a_routes.go":                       "// Code generated by muxt generate --output-htmx. DO NOT EDIT.\n// muxt version: v1.0.0\n\npackage a\n",
		"b_routes.go":                       "// Code generated by muxt generate --logger. DO NOT EDIT.\n\npackage a\n",
		"handwritten.go":                    "package a\n",
		"empty.go":                          "",
		"notes.txt":                         "// Code generated by muxt generate --logger. DO NOT EDIT.\n",
		"nested/deep/routes.go":             "// Code generated by muxt generate --use-receiver-type=T. DO NOT EDIT.\n",
		"other/generated_by_stringer.go":    "// Code generated by stringer. DO NOT EDIT.\n",
		"vendor/v/routes.go":                "// Code generated by muxt generate --logger. DO NOT EDIT.\n",
		"node_modules/n/routes.go":          "// Code generated by muxt generate --logger. DO NOT EDIT.\n",
		"testdata/t/routes.go":              "// Code generated by muxt generate --logger. DO NOT EDIT.\n",
		".git/g/routes.go":                  "// Code generated by muxt generate --logger. DO NOT EDIT.\n",
		"nested/testdata/skipped/routes.go": "// Code generated by muxt generate --logger. DO NOT EDIT.\n",
	})

	got, err := scanGeneratedHeaders(dir)
	require.NoError(t, err)

	assert.Equal(t, map[string]headerEntry{
		dir: {
			dir:         dir,
			args:        []string{"--output-htmx"},
			command:     "--output-htmx",
			muxtVersion: "v1.0.0",
		},
		filepath.Join(dir, "nested", "deep"): {
			dir:     filepath.Join(dir, "nested", "deep"),
			args:    []string{"--use-receiver-type=T"},
			command: "--use-receiver-type=T",
		},
	}, got, "one entry per directory, the first file wins, and skipped directories are not walked")

	_, err = scanGeneratedHeaders(filepath.Join(dir, "missing"))
	assert.Error(t, err)
}

func TestNewPackageInfo(t *testing.T) {
	moduleDir := t.TempDir()
	writeFiles(t, moduleDir, map[string]string{
		"page.gohtml":       `<script src="https://cdn.example.com/x.js"></script>`,
		"sub/page.gohtml":   `<p>no assets</p>`,
		"sub/routes.go":     "package sub\n",
		"other/page.gohtml": `<a href="http://example.com/a">a</a>`,
	})
	mod := goModule{Path: "example.com/app", Dir: moduleDir}
	config := PackageConfig{RoutesFunction: "TemplateRoutes"}

	for _, tt := range []struct {
		name     string
		entry    headerEntry
		wantPath string
		assets   int
	}{
		{name: "module root", entry: headerEntry{dir: moduleDir, command: "--logger", muxtVersion: "v1"}, wantPath: "example.com/app", assets: 1},
		{name: "subdirectory", entry: headerEntry{dir: filepath.Join(moduleDir, "sub")}, wantPath: "example.com/app/sub"},
		{name: "nested", entry: headerEntry{dir: filepath.Join(moduleDir, "other")}, wantPath: "example.com/app/other", assets: 1},
	} {
		t.Run(tt.name, func(t *testing.T) {
			got, err := newPackageInfo(mod, tt.entry, config)
			require.NoError(t, err)
			assert.Equal(t, tt.wantPath, got.Path, "newPackageInfo path")
			assert.Equal(t, tt.entry.dir, got.Dir)
			assert.Equal(t, tt.entry.muxtVersion, got.MuxtVersion)
			assert.Equal(t, config, got.Config)
			assert.Equal(t, buildCommands(tt.entry.dir, tt.entry.command), got.Commands)
			assert.Len(t, got.ExternalAssets, tt.assets)
		})
	}

	_, err := newPackageInfo(mod, headerEntry{dir: filepath.Join(moduleDir, "missing")}, config)
	assert.Error(t, err, "a directory that cannot be read")
}

func TestBuildCommands(t *testing.T) {
	for _, tt := range []struct {
		name, dir, command string
		want               PackageCommands
	}{
		{
			name: "no arguments", dir: "/m/p",
			want: PackageCommands{
				ListRoutes: "muxt -C /m/p",
				Calls:      "muxt -C /m/p list-template-calls",
				Callers:    "muxt -C /m/p list-template-callers",
				Check:      "muxt -C /m/p check",
				Generate:   "muxt -C /m/p generate",
			},
		},
		{
			name: "arguments", dir: "/m/p", command: "--use-receiver-type=T --logger",
			want: PackageCommands{
				ListRoutes: "muxt -C /m/p",
				Calls:      "muxt -C /m/p list-template-calls",
				Callers:    "muxt -C /m/p list-template-callers",
				Check:      "muxt -C /m/p check",
				Generate:   "muxt -C /m/p generate --use-receiver-type=T --logger",
			},
		},
	} {
		t.Run(tt.name, func(t *testing.T) {
			got := buildCommands(tt.dir, tt.command)
			assert.Equal(t, tt.want, got, "buildCommands(%q, %q)", tt.dir, tt.command)
		})
	}
}

func TestFindExternalAssets(t *testing.T) {
	dir := t.TempDir()
	writeFiles(t, dir, map[string]string{
		"a.gohtml":     "<p>none</p>\n<link href=\"https://cdn.example.com/s.css\"> <img src='http://img.example.com/i.png'>\n",
		"b.gohtml":     "{{define \"x\"}}<script src=\"https://cdn.example.com/x.js\"></script>{{end}}",
		"c.html":       `<a href="https://ignored.example.com">not a gohtml file</a>`,
		"sub/d.gohtml": `<a href="https://ignored.example.com">not in this directory</a>`,
	})

	got, err := findExternalAssets(dir)
	require.NoError(t, err)

	assert.Equal(t, []ExternalAsset{
		{URL: "https://cdn.example.com/s.css", File: filepath.Join(dir, "a.gohtml"), Line: 2, StartCol: 13, EndCol: 41},
		{URL: "http://img.example.com/i.png", File: filepath.Join(dir, "a.gohtml"), Line: 2, StartCol: 55, EndCol: 82},
		{URL: "https://cdn.example.com/x.js", File: filepath.Join(dir, "b.gohtml"), Line: 1, StartCol: 28, EndCol: 55},
	}, got)

	_, err = findExternalAssets(filepath.Join(dir, "missing"))
	assert.Error(t, err)
}

func TestScanFileForExternalAssets(t *testing.T) {
	dir := t.TempDir()
	writeFiles(t, dir, map[string]string{"a.gohtml": "https://a.example.com and https://b.example.com/x?y=1\n\nhttp://c.example.com"})
	path := filepath.Join(dir, "a.gohtml")

	got, err := scanFileForExternalAssets(path)
	require.NoError(t, err)
	assert.Equal(t, []ExternalAsset{
		{URL: "https://a.example.com", File: path, Line: 1, StartCol: 1, EndCol: 21},
		{URL: "https://b.example.com/x?y=1", File: path, Line: 1, StartCol: 27, EndCol: 53},
		{URL: "http://c.example.com", File: path, Line: 3, StartCol: 1, EndCol: 20},
	}, got)

	_, err = scanFileForExternalAssets(filepath.Join(dir, "missing.gohtml"))
	assert.Error(t, err)
}
