package analysis

import (
	"bufio"
	"bytes"
	"encoding/json/v2"
	"io"
	"maps"
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
	"slices"
	"strings"

	"github.com/typelate/muxt/internal/header"
)

type Module struct {
	ModulePath string        `json:"module"`
	ModuleDir  string        `json:"moduleDir"`
	Packages   []PackageInfo `json:"packages"`
}

type PackageInfo struct {
	Path           string          `json:"path"`
	Dir            string          `json:"dir"`
	MuxtVersion    string          `json:"muxtVersion,omitempty"`
	Config         PackageConfig   `json:"config"`
	Commands       PackageCommands `json:"commands"`
	ExternalAssets []ExternalAsset `json:"externalAssets,omitempty"`
}

type PackageConfig struct {
	RoutesFunction         string `json:"routesFunction"`
	ReceiverInterface      string `json:"receiverInterface"`
	ReceiverType           string `json:"receiverType,omitempty"`
	ReceiverPackage        string `json:"receiverPackage,omitempty"`
	TemplateRoutePathsType string `json:"templateRoutePathsType"`
	OutputHTMX             bool   `json:"outputHTMX,omitzero"`
	OutputDatastar         bool   `json:"outputDatastar,omitzero"`
	Logger                 bool   `json:"logger,omitzero"`
	PathPrefix             bool   `json:"pathPrefix,omitzero"`
	Middleware             bool   `json:"middleware,omitzero"`
}

type PackageCommands struct {
	ListRoutes string `json:"listRoutes"`
	Calls      string `json:"calls"`
	Callers    string `json:"callers"`
	Check      string `json:"check"`
	Generate   string `json:"generate"`
}

type ExternalAsset struct {
	URL      string `json:"url"`
	File     string `json:"file"`
	Line     int    `json:"line"`
	StartCol int    `json:"startCol"`
	EndCol   int    `json:"endCol"`
}

func (m *Module) WriteTo(w io.Writer) (int64, error) {
	var buf bytes.Buffer
	if err := templates.ExecuteTemplate(&buf, "module.txt.template", m); err != nil {
		return 0, err
	}
	return io.Copy(w, &buf)
}

type goModule struct {
	Path string `json:"Path"`
	Dir  string `json:"Dir"`
}

// headerEntry is the generated-file header found in a directory.
type headerEntry struct {
	dir         string
	args        []string
	command     string // raw args string from the header comment
	muxtVersion string
}

// NewModule lists the muxt packages of the module that contains
// workingDirectory: the directories holding a generated file. parseHeader
// turns the arguments recorded in a header into the package's configuration
// and reports false when they do not parse, which skips the directory.
func NewModule(workingDirectory string, parseHeader func(args []string) (PackageConfig, bool)) (*Module, error) {
	mod, err := listModule(workingDirectory)
	if err != nil {
		return nil, err
	}
	entries, err := scanGeneratedHeaders(mod.Dir)
	if err != nil {
		return nil, err
	}

	var packages []PackageInfo
	for _, dir := range slices.Sorted(maps.Keys(entries)) {
		entry := entries[dir]
		config, ok := parseHeader(entry.args)
		if !ok {
			continue
		}
		info, err := newPackageInfo(mod, entry, config)
		if err != nil {
			return nil, err
		}
		packages = append(packages, info)
	}

	return &Module{
		ModulePath: mod.Path,
		ModuleDir:  mod.Dir,
		Packages:   packages,
	}, nil
}

// listModule runs go list in workingDirectory.
func listModule(workingDirectory string) (goModule, error) {
	cmd := exec.Command("go", "list", "-m", "-json")
	cmd.Dir = workingDirectory
	out, err := cmd.Output()
	if err != nil {
		return goModule{}, err
	}
	var mod goModule
	if err := json.Unmarshal(out, &mod); err != nil {
		return goModule{}, err
	}
	return mod, nil
}

// scanGeneratedHeaders walks the tree at moduleDir and returns, for each
// directory holding a file generated by muxt, the header of the first one.
func scanGeneratedHeaders(moduleDir string) (map[string]headerEntry, error) {
	entries := make(map[string]headerEntry)
	err := filepath.WalkDir(moduleDir, func(path string, d os.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if d.IsDir() {
			base := d.Name()
			if base == ".git" || base == "vendor" || base == "node_modules" || base == "testdata" {
				return filepath.SkipDir
			}
			return nil
		}
		if !strings.HasSuffix(d.Name(), ".go") {
			return nil
		}

		f, err := os.Open(path)
		if err != nil {
			return err
		}
		defer func() { _ = f.Close() }()
		scanner := bufio.NewScanner(f)
		var (
			lines     [2]string
			lineCount int
		)
		for lineCount < len(lines) && scanner.Scan() {
			lines[lineCount] = scanner.Text()
			lineCount++
		}
		if lineCount == 0 {
			return nil
		}

		parsed, ok := header.Parse(lines[0], lines[1])
		if !ok {
			return nil
		}

		dir := filepath.Dir(path)
		if _, ok := entries[dir]; !ok {
			entries[dir] = headerEntry{dir: dir, args: parsed.Args(), command: parsed.Command, muxtVersion: parsed.Version}
		}

		return nil
	})
	if err != nil {
		return nil, err
	}
	return entries, nil
}

// newPackageInfo describes the package in entry's directory.
func newPackageInfo(mod goModule, entry headerEntry, config PackageConfig) (PackageInfo, error) {
	relDir, err := filepath.Rel(mod.Dir, entry.dir)
	if err != nil {
		return PackageInfo{}, err
	}
	pkgPath := mod.Path
	if relDir != "." {
		pkgPath = mod.Path + "/" + filepath.ToSlash(relDir)
	}

	assets, err := findExternalAssets(entry.dir)
	if err != nil {
		return PackageInfo{}, err
	}

	return PackageInfo{
		Path:           pkgPath,
		Dir:            entry.dir,
		MuxtVersion:    entry.muxtVersion,
		Config:         config,
		Commands:       buildCommands(entry.dir, entry.command),
		ExternalAssets: assets,
	}, nil
}

func buildCommands(dir string, headerCommand string) PackageCommands {
	cFlag := "muxt -C " + dir

	gen := cFlag + " generate"
	if headerCommand != "" {
		gen += " " + headerCommand
	}

	return PackageCommands{
		ListRoutes: cFlag,
		Calls:      cFlag + " list-template-calls",
		Callers:    cFlag + " list-template-callers",
		Check:      cFlag + " check",
		Generate:   gen,
	}
}

var externalURLPattern = regexp.MustCompile(`https?://[^\s"'<>` + "`" + `]+`)

func findExternalAssets(dir string) ([]ExternalAsset, error) {
	entries, err := os.ReadDir(dir)
	if err != nil {
		return nil, err
	}

	var assets []ExternalAsset
	for _, entry := range entries {
		if entry.IsDir() || !strings.HasSuffix(entry.Name(), ".gohtml") {
			continue
		}

		filePath := filepath.Join(dir, entry.Name())
		fileAssets, err := scanFileForExternalAssets(filePath)
		if err != nil {
			return nil, err
		}
		assets = append(assets, fileAssets...)
	}

	return assets, nil
}

func scanFileForExternalAssets(filePath string) ([]ExternalAsset, error) {
	f, err := os.Open(filePath)
	if err != nil {
		return nil, err
	}
	defer func() { _ = f.Close() }()

	var assets []ExternalAsset
	scanner := bufio.NewScanner(f)
	lineNum := 0
	for scanner.Scan() {
		lineNum++
		line := scanner.Text()
		locs := externalURLPattern.FindAllStringIndex(line, -1)
		for _, loc := range locs {
			assets = append(assets, ExternalAsset{
				URL:      line[loc[0]:loc[1]],
				File:     filePath,
				Line:     lineNum,
				StartCol: loc[0] + 1,
				EndCol:   loc[1],
			})
		}
	}
	if err := scanner.Err(); err != nil {
		return nil, err
	}
	return assets, nil
}
