package analysis

import (
	"bufio"
	"bytes"
	"encoding/json"
	"io"
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
	"sort"
	"strings"

	"github.com/spf13/pflag"

	"github.com/typelate/muxt/internal/generate"
)

type Module struct {
	ModulePath string        `json:"module"`
	ModuleDir  string        `json:"moduleDir"`
	Packages   []PackageInfo `json:"packages"`
}

type PackageInfo struct {
	Path           string          `json:"path"`
	Dir            string          `json:"dir"`
	MuxtVersion    string          `json:"muxtVersion,omitempty"`
	Config         PackageConfig   `json:"config"`
	Commands       PackageCommands `json:"commands"`
	ExternalAssets []ExternalAsset `json:"externalAssets,omitempty"`
}

type PackageConfig struct {
	RoutesFunction         string `json:"routesFunction"`
	ReceiverInterface      string `json:"receiverInterface"`
	ReceiverType           string `json:"receiverType,omitempty"`
	ReceiverPackage        string `json:"receiverPackage,omitempty"`
	TemplateRoutePathsType string `json:"templateRoutePathsType"`
	HTMXHelpers            bool   `json:"htmxHelpers,omitempty"`
	Logger                 bool   `json:"logger,omitempty"`
	PathPrefix             bool   `json:"pathPrefix,omitempty"`
}

type PackageCommands struct {
	ListRoutes string `json:"listRoutes"`
	Calls      string `json:"calls"`
	Callers    string `json:"callers"`
	Check      string `json:"check"`
	Generate   string `json:"generate"`
}

type ExternalAsset struct {
	URL      string `json:"url"`
	File     string `json:"file"`
	Line     int    `json:"line"`
	StartCol int    `json:"startCol"`
	EndCol   int    `json:"endCol"`
}

func (m *Module) WriteTo(w io.Writer) (int64, error) {
	var buf bytes.Buffer
	if err := templates.ExecuteTemplate(&buf, "module.txt.template", m); err != nil {
		return 0, err
	}
	return io.Copy(w, &buf)
}

type goListModule struct {
	Path string `json:"Path"`
	Dir  string `json:"Dir"`
}

func NewModule(workingDirectory string, addFlags func(*pflag.FlagSet, *generate.RoutesFileConfiguration)) (*Module, error) {
	cmd := exec.Command("go", "list", "-m", "-json")
	cmd.Dir = workingDirectory
	out, err := cmd.Output()
	if err != nil {
		return nil, err
	}
	var mod goListModule
	if err := json.Unmarshal(out, &mod); err != nil {
		return nil, err
	}

	// Walk the module tree looking for generated files
	type dirEntry struct {
		dir         string
		args        []string
		command     string // raw args string from the header comment
		muxtVersion string
	}
	dirMap := make(map[string]*dirEntry)

	err = filepath.WalkDir(mod.Dir, func(path string, d os.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if d.IsDir() {
			base := d.Name()
			if base == ".git" || base == "vendor" || base == "node_modules" || base == "testdata" {
				return filepath.SkipDir
			}
			return nil
		}
		if !strings.HasSuffix(d.Name(), ".go") {
			return nil
		}

		f, err := os.Open(path)
		if err != nil {
			return err
		}
		defer func() { _ = f.Close() }()
		scanner := bufio.NewScanner(f)
		var (
			lines     [2]string
			lineCount int
		)
		for lineCount < len(lines) && scanner.Scan() {
			lines[lineCount] = scanner.Text()
			lineCount++
		}
		if lineCount == 0 {
			return nil
		}

		const prefix = "// Code generated by muxt generate "
		const suffix = ". DO NOT EDIT."

		if !strings.HasPrefix(lines[0], prefix) || !strings.HasSuffix(lines[0], suffix) {
			return nil
		}

		command := strings.TrimPrefix(lines[0], prefix)
		command = strings.TrimSuffix(command, suffix)

		const versionPrefix = "// muxt version: "
		var version string
		if lineCount > 1 && strings.HasPrefix(lines[1], versionPrefix) {
			version = strings.TrimPrefix(lines[1], versionPrefix)
		}

		dir := filepath.Dir(path)
		if _, ok := dirMap[dir]; !ok {
			dirMap[dir] = &dirEntry{dir: dir, args: strings.Fields(command), command: command, muxtVersion: version}
		}

		return nil
	})
	if err != nil {
		return nil, err
	}

	dirs := make([]string, 0, len(dirMap))
	for dir := range dirMap {
		dirs = append(dirs, dir)
	}
	sort.Strings(dirs)

	var packages []PackageInfo
	for _, dir := range dirs {
		entry := dirMap[dir]
		var config generate.RoutesFileConfiguration
		set := pflag.NewFlagSet("parse-header", pflag.ContinueOnError)
		set.SetOutput(io.Discard)
		addFlags(set, &config)
		if err := set.Parse(entry.args); err != nil {
			continue
		}

		// Apply defaults for empty fields
		routesFunction := config.RoutesFunction
		if routesFunction == "" {
			routesFunction = generate.DefaultRoutesFunctionName
		}
		receiverInterface := config.ReceiverInterface
		if receiverInterface == "" {
			receiverInterface = generate.DefaultReceiverInterfaceName
		}
		templateRoutePathsType := config.TemplateRoutePathsTypeName
		if templateRoutePathsType == "" {
			templateRoutePathsType = generate.DefaultTemplateRoutePathsTypeName
		}

		// Compute package import path from module path + relative dir
		relDir, err := filepath.Rel(mod.Dir, entry.dir)
		if err != nil {
			return nil, err
		}
		pkgPath := mod.Path
		if relDir != "." {
			pkgPath = mod.Path + "/" + filepath.ToSlash(relDir)
		}

		// Build commands
		commands := buildCommands(entry.dir, entry.command)

		// Scan for external assets
		assets, err := findExternalAssets(entry.dir)
		if err != nil {
			return nil, err
		}

		packages = append(packages, PackageInfo{
			Path:        pkgPath,
			Dir:         entry.dir,
			MuxtVersion: entry.muxtVersion,
			Config: PackageConfig{
				RoutesFunction:         routesFunction,
				ReceiverInterface:      receiverInterface,
				ReceiverType:           config.ReceiverType,
				ReceiverPackage:        config.ReceiverPackage,
				TemplateRoutePathsType: templateRoutePathsType,
				HTMXHelpers:            config.HTMXHelpers,
				Logger:                 config.Logger,
				PathPrefix:             config.PathPrefix,
			},
			Commands:       commands,
			ExternalAssets: assets,
		})
	}

	return &Module{
		ModulePath: mod.Path,
		ModuleDir:  mod.Dir,
		Packages:   packages,
	}, nil
}

func buildCommands(dir string, headerCommand string) PackageCommands {
	cFlag := "muxt -C " + dir

	gen := cFlag + " generate"
	if headerCommand != "" {
		gen += " " + headerCommand
	}

	return PackageCommands{
		ListRoutes: cFlag,
		Calls:      cFlag + " list-template-calls",
		Callers:    cFlag + " list-template-callers",
		Check:      cFlag + " check",
		Generate:   gen,
	}
}

var externalURLPattern = regexp.MustCompile(`https?://[^\s"'<>` + "`" + `]+`)

func findExternalAssets(dir string) ([]ExternalAsset, error) {
	entries, err := os.ReadDir(dir)
	if err != nil {
		return nil, err
	}

	var assets []ExternalAsset
	for _, entry := range entries {
		if entry.IsDir() || !strings.HasSuffix(entry.Name(), ".gohtml") {
			continue
		}

		filePath := filepath.Join(dir, entry.Name())
		fileAssets, err := scanFileForExternalAssets(filePath)
		if err != nil {
			return nil, err
		}
		assets = append(assets, fileAssets...)
	}

	return assets, nil
}

func scanFileForExternalAssets(filePath string) ([]ExternalAsset, error) {
	f, err := os.Open(filePath)
	if err != nil {
		return nil, err
	}
	defer func() { _ = f.Close() }()

	var assets []ExternalAsset
	scanner := bufio.NewScanner(f)
	lineNum := 0
	for scanner.Scan() {
		lineNum++
		line := scanner.Text()
		locs := externalURLPattern.FindAllStringIndex(line, -1)
		for _, loc := range locs {
			assets = append(assets, ExternalAsset{
				URL:      line[loc[0]:loc[1]],
				File:     filePath,
				Line:     lineNum,
				StartCol: loc[0] + 1,
				EndCol:   loc[1],
			})
		}
	}
	if err := scanner.Err(); err != nil {
		return nil, err
	}
	return assets, nil
}
