package analysis

import (
	"go/types"
	"os"
	"path/filepath"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"github.com/typelate/check"

	"github.com/typelate/muxt/internal/source"
)

func TestIndent(t *testing.T) {
	for _, tt := range []struct{ in, want string }{
		{in: "", want: "> "},
		{in: "a", want: "> a"},
		{in: "a\nb", want: "> a\n> b"},
		{in: "a\n", want: "> a\n> "},
	} {
		assert.Equal(t, tt.want, indent("> ", tt.in), "indent(%q)", tt.in)
	}
}

func TestNewRoutesSkipsTemplatesWithoutATree(t *testing.T) {
	ts := parseTemplates(t, `{{define "GET /a A()"}}a{{end}}`)
	ts.New("GET /b B()") // declared, never parsed: no tree
	pkg := source.Package{Variables: []source.Variable{{Name: "templates", Set: ts}}}
	results, err := NewRoutes(pkg, nil)
	require.NoError(t, err)
	require.Len(t, results, 1)
	require.Len(t, results[0].Definitions, 1)
	assert.Equal(t, "GET /a A()", results[0].Definitions[0].String)
}

func TestCheckFindsTemplatesWithoutATree(t *testing.T) {
	ts := parseTemplates(t, `{{define "root"}}{{template "missing" .}}{{template "declared" .}}{{end}}`)
	ts.New("declared") // declared, never parsed: no tree
	global := newGlobal(source.Package{Types: types.NewPackage("example.com/p", "p")}, source.Variable{Name: "templates", Set: ts})
	err := check.Execute(global, ts.Lookup("root").Tree, types.Typ[types.Int])
	require.Error(t, err)
	assert.Contains(t, err.Error(), "missing")
}

func TestNewModule(t *testing.T) {
	root := t.TempDir()
	writeFiles(t, root, map[string]string{
		"go.mod":               "module example.com/m\n\ngo 1.24\n",
		"routes.go":            "// Code generated by muxt generate --output-htmx. DO NOT EDIT.\n\npackage m\n",
		"sub/routes.go":        "// Code generated by muxt generate --logger. DO NOT EDIT.\n\npackage sub\n",
		"unparsed/routes.go":   "// Code generated by muxt generate --bogus. DO NOT EDIT.\n\npackage unparsed\n",
		"plain/handwritten.go": "package plain\n",
	})
	parseHeader := func(args []string) (PackageConfig, bool) {
		switch args[0] {
		case "--output-htmx":
			return PackageConfig{OutputHTMX: true}, true
		case "--logger":
			return PackageConfig{Logger: true}, true
		}
		return PackageConfig{}, false
	}

	mod, err := NewModule(root, parseHeader)
	require.NoError(t, err)
	assert.Equal(t, "example.com/m", mod.ModulePath)
	moduleDir, err := filepath.EvalSymlinks(mod.ModuleDir)
	require.NoError(t, err)
	wantDir, err := filepath.EvalSymlinks(root)
	require.NoError(t, err)
	assert.Equal(t, wantDir, moduleDir)
	require.Len(t, mod.Packages, 2, "the directory whose header does not parse is skipped")
	assert.Equal(t, "example.com/m", mod.Packages[0].Path)
	assert.True(t, mod.Packages[0].Config.OutputHTMX)
	assert.Equal(t, "example.com/m/sub", mod.Packages[1].Path)
	assert.True(t, mod.Packages[1].Config.Logger)
}

func TestNewModuleOutsideAModule(t *testing.T) {
	t.Setenv("GOWORK", "off")
	_, err := NewModule(t.TempDir(), func([]string) (PackageConfig, bool) { return PackageConfig{}, true })
	assert.Error(t, err)
}

func TestNewModuleReportsUnreadableFiles(t *testing.T) {
	if os.Geteuid() == 0 {
		t.Skip("file permissions do not restrict root")
	}
	accept := func([]string) (PackageConfig, bool) { return PackageConfig{}, true }
	for _, tt := range []struct {
		name       string
		unreadable string
	}{
		{name: "a Go file whose header cannot be read", unreadable: "sub/other.go"},
		{name: "a template scanned for external assets", unreadable: "page.gohtml"},
	} {
		t.Run(tt.name, func(t *testing.T) {
			t.Setenv("GOWORK", "off")
			root := t.TempDir()
			writeFiles(t, root, map[string]string{
				"go.mod":       "module example.com/m\n\ngo 1.24\n",
				"routes.go":    "// Code generated by muxt generate --logger. DO NOT EDIT.\n\npackage m\n",
				"sub/other.go": "package sub\n",
				"page.gohtml":  "<p>hi</p>",
			})
			require.NoError(t, os.Chmod(filepath.Join(root, filepath.FromSlash(tt.unreadable)), 0))
			_, err := NewModule(root, accept)
			assert.Error(t, err)
		})
	}
}
