// Code generated by counterfeiter. DO NOT EDIT.
package muxtfakes

import (
	"go/types"
	"sync"

	"github.com/typelate/muxt/internal/muxt"
)

type FakeChecker struct {
	FileHeaderStub        func() (types.Type, error)
	fileHeaderMutex       sync.RWMutex
	fileHeaderArgsForCall []struct {
	}
	fileHeaderReturns struct {
		result1 types.Type
		result2 error
	}
	fileHeaderReturnsOnCall map[int]struct {
		result1 types.Type
		result2 error
	}
	RawJSONStub        func() (types.Type, error)
	rawJSONMutex       sync.RWMutex
	rawJSONArgsForCall []struct {
	}
	rawJSONReturns struct {
		result1 types.Type
		result2 error
	}
	rawJSONReturnsOnCall map[int]struct {
		result1 types.Type
		result2 error
	}
	ScopeTypeStub        func(string) (types.Type, error)
	scopeTypeMutex       sync.RWMutex
	scopeTypeArgsForCall []struct {
		arg1 string
	}
	scopeTypeReturns struct {
		result1 types.Type
		result2 error
	}
	scopeTypeReturnsOnCall map[int]struct {
		result1 types.Type
		result2 error
	}
	TextMarshalerStub        func(types.Type) bool
	textMarshalerMutex       sync.RWMutex
	textMarshalerArgsForCall []struct {
		arg1 types.Type
	}
	textMarshalerReturns struct {
		result1 bool
	}
	textMarshalerReturnsOnCall map[int]struct {
		result1 bool
	}
	TextUnmarshalerStub        func(types.Type) bool
	textUnmarshalerMutex       sync.RWMutex
	textUnmarshalerArgsForCall []struct {
		arg1 types.Type
	}
	textUnmarshalerReturns struct {
		result1 bool
	}
	textUnmarshalerReturnsOnCall map[int]struct {
		result1 bool
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeChecker) FileHeader() (types.Type, error) {
	fake.fileHeaderMutex.Lock()
	ret, specificReturn := fake.fileHeaderReturnsOnCall[len(fake.fileHeaderArgsForCall)]
	fake.fileHeaderArgsForCall = append(fake.fileHeaderArgsForCall, struct {
	}{})
	stub := fake.FileHeaderStub
	fakeReturns := fake.fileHeaderReturns
	fake.recordInvocation("FileHeader", []interface{}{})
	fake.fileHeaderMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeChecker) FileHeaderCallCount() int {
	fake.fileHeaderMutex.RLock()
	defer fake.fileHeaderMutex.RUnlock()
	return len(fake.fileHeaderArgsForCall)
}

func (fake *FakeChecker) FileHeaderCalls(stub func() (types.Type, error)) {
	fake.fileHeaderMutex.Lock()
	defer fake.fileHeaderMutex.Unlock()
	fake.FileHeaderStub = stub
}

func (fake *FakeChecker) FileHeaderReturns(result1 types.Type, result2 error) {
	fake.fileHeaderMutex.Lock()
	defer fake.fileHeaderMutex.Unlock()
	fake.FileHeaderStub = nil
	fake.fileHeaderReturns = struct {
		result1 types.Type
		result2 error
	}{result1, result2}
}

func (fake *FakeChecker) FileHeaderReturnsOnCall(i int, result1 types.Type, result2 error) {
	fake.fileHeaderMutex.Lock()
	defer fake.fileHeaderMutex.Unlock()
	fake.FileHeaderStub = nil
	if fake.fileHeaderReturnsOnCall == nil {
		fake.fileHeaderReturnsOnCall = make(map[int]struct {
			result1 types.Type
			result2 error
		})
	}
	fake.fileHeaderReturnsOnCall[i] = struct {
		result1 types.Type
		result2 error
	}{result1, result2}
}

func (fake *FakeChecker) RawJSON() (types.Type, error) {
	fake.rawJSONMutex.Lock()
	ret, specificReturn := fake.rawJSONReturnsOnCall[len(fake.rawJSONArgsForCall)]
	fake.rawJSONArgsForCall = append(fake.rawJSONArgsForCall, struct {
	}{})
	stub := fake.RawJSONStub
	fakeReturns := fake.rawJSONReturns
	fake.recordInvocation("RawJSON", []interface{}{})
	fake.rawJSONMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeChecker) RawJSONCallCount() int {
	fake.rawJSONMutex.RLock()
	defer fake.rawJSONMutex.RUnlock()
	return len(fake.rawJSONArgsForCall)
}

func (fake *FakeChecker) RawJSONCalls(stub func() (types.Type, error)) {
	fake.rawJSONMutex.Lock()
	defer fake.rawJSONMutex.Unlock()
	fake.RawJSONStub = stub
}

func (fake *FakeChecker) RawJSONReturns(result1 types.Type, result2 error) {
	fake.rawJSONMutex.Lock()
	defer fake.rawJSONMutex.Unlock()
	fake.RawJSONStub = nil
	fake.rawJSONReturns = struct {
		result1 types.Type
		result2 error
	}{result1, result2}
}

func (fake *FakeChecker) RawJSONReturnsOnCall(i int, result1 types.Type, result2 error) {
	fake.rawJSONMutex.Lock()
	defer fake.rawJSONMutex.Unlock()
	fake.RawJSONStub = nil
	if fake.rawJSONReturnsOnCall == nil {
		fake.rawJSONReturnsOnCall = make(map[int]struct {
			result1 types.Type
			result2 error
		})
	}
	fake.rawJSONReturnsOnCall[i] = struct {
		result1 types.Type
		result2 error
	}{result1, result2}
}

func (fake *FakeChecker) ScopeType(arg1 string) (types.Type, error) {
	fake.scopeTypeMutex.Lock()
	ret, specificReturn := fake.scopeTypeReturnsOnCall[len(fake.scopeTypeArgsForCall)]
	fake.scopeTypeArgsForCall = append(fake.scopeTypeArgsForCall, struct {
		arg1 string
	}{arg1})
	stub := fake.ScopeTypeStub
	fakeReturns := fake.scopeTypeReturns
	fake.recordInvocation("ScopeType", []interface{}{arg1})
	fake.scopeTypeMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeChecker) ScopeTypeCallCount() int {
	fake.scopeTypeMutex.RLock()
	defer fake.scopeTypeMutex.RUnlock()
	return len(fake.scopeTypeArgsForCall)
}

func (fake *FakeChecker) ScopeTypeCalls(stub func(string) (types.Type, error)) {
	fake.scopeTypeMutex.Lock()
	defer fake.scopeTypeMutex.Unlock()
	fake.ScopeTypeStub = stub
}

func (fake *FakeChecker) ScopeTypeArgsForCall(i int) string {
	fake.scopeTypeMutex.RLock()
	defer fake.scopeTypeMutex.RUnlock()
	argsForCall := fake.scopeTypeArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeChecker) ScopeTypeReturns(result1 types.Type, result2 error) {
	fake.scopeTypeMutex.Lock()
	defer fake.scopeTypeMutex.Unlock()
	fake.ScopeTypeStub = nil
	fake.scopeTypeReturns = struct {
		result1 types.Type
		result2 error
	}{result1, result2}
}

func (fake *FakeChecker) ScopeTypeReturnsOnCall(i int, result1 types.Type, result2 error) {
	fake.scopeTypeMutex.Lock()
	defer fake.scopeTypeMutex.Unlock()
	fake.ScopeTypeStub = nil
	if fake.scopeTypeReturnsOnCall == nil {
		fake.scopeTypeReturnsOnCall = make(map[int]struct {
			result1 types.Type
			result2 error
		})
	}
	fake.scopeTypeReturnsOnCall[i] = struct {
		result1 types.Type
		result2 error
	}{result1, result2}
}

func (fake *FakeChecker) TextMarshaler(arg1 types.Type) bool {
	fake.textMarshalerMutex.Lock()
	ret, specificReturn := fake.textMarshalerReturnsOnCall[len(fake.textMarshalerArgsForCall)]
	fake.textMarshalerArgsForCall = append(fake.textMarshalerArgsForCall, struct {
		arg1 types.Type
	}{arg1})
	stub := fake.TextMarshalerStub
	fakeReturns := fake.textMarshalerReturns
	fake.recordInvocation("TextMarshaler", []interface{}{arg1})
	fake.textMarshalerMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeChecker) TextMarshalerCallCount() int {
	fake.textMarshalerMutex.RLock()
	defer fake.textMarshalerMutex.RUnlock()
	return len(fake.textMarshalerArgsForCall)
}

func (fake *FakeChecker) TextMarshalerCalls(stub func(types.Type) bool) {
	fake.textMarshalerMutex.Lock()
	defer fake.textMarshalerMutex.Unlock()
	fake.TextMarshalerStub = stub
}

func (fake *FakeChecker) TextMarshalerArgsForCall(i int) types.Type {
	fake.textMarshalerMutex.RLock()
	defer fake.textMarshalerMutex.RUnlock()
	argsForCall := fake.textMarshalerArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeChecker) TextMarshalerReturns(result1 bool) {
	fake.textMarshalerMutex.Lock()
	defer fake.textMarshalerMutex.Unlock()
	fake.TextMarshalerStub = nil
	fake.textMarshalerReturns = struct {
		result1 bool
	}{result1}
}

func (fake *FakeChecker) TextMarshalerReturnsOnCall(i int, result1 bool) {
	fake.textMarshalerMutex.Lock()
	defer fake.textMarshalerMutex.Unlock()
	fake.TextMarshalerStub = nil
	if fake.textMarshalerReturnsOnCall == nil {
		fake.textMarshalerReturnsOnCall = make(map[int]struct {
			result1 bool
		})
	}
	fake.textMarshalerReturnsOnCall[i] = struct {
		result1 bool
	}{result1}
}

func (fake *FakeChecker) TextUnmarshaler(arg1 types.Type) bool {
	fake.textUnmarshalerMutex.Lock()
	ret, specificReturn := fake.textUnmarshalerReturnsOnCall[len(fake.textUnmarshalerArgsForCall)]
	fake.textUnmarshalerArgsForCall = append(fake.textUnmarshalerArgsForCall, struct {
		arg1 types.Type
	}{arg1})
	stub := fake.TextUnmarshalerStub
	fakeReturns := fake.textUnmarshalerReturns
	fake.recordInvocation("TextUnmarshaler", []interface{}{arg1})
	fake.textUnmarshalerMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeChecker) TextUnmarshalerCallCount() int {
	fake.textUnmarshalerMutex.RLock()
	defer fake.textUnmarshalerMutex.RUnlock()
	return len(fake.textUnmarshalerArgsForCall)
}

func (fake *FakeChecker) TextUnmarshalerCalls(stub func(types.Type) bool) {
	fake.textUnmarshalerMutex.Lock()
	defer fake.textUnmarshalerMutex.Unlock()
	fake.TextUnmarshalerStub = stub
}

func (fake *FakeChecker) TextUnmarshalerArgsForCall(i int) types.Type {
	fake.textUnmarshalerMutex.RLock()
	defer fake.textUnmarshalerMutex.RUnlock()
	argsForCall := fake.textUnmarshalerArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeChecker) TextUnmarshalerReturns(result1 bool) {
	fake.textUnmarshalerMutex.Lock()
	defer fake.textUnmarshalerMutex.Unlock()
	fake.TextUnmarshalerStub = nil
	fake.textUnmarshalerReturns = struct {
		result1 bool
	}{result1}
}

func (fake *FakeChecker) TextUnmarshalerReturnsOnCall(i int, result1 bool) {
	fake.textUnmarshalerMutex.Lock()
	defer fake.textUnmarshalerMutex.Unlock()
	fake.TextUnmarshalerStub = nil
	if fake.textUnmarshalerReturnsOnCall == nil {
		fake.textUnmarshalerReturnsOnCall = make(map[int]struct {
			result1 bool
		})
	}
	fake.textUnmarshalerReturnsOnCall[i] = struct {
		result1 bool
	}{result1}
}

func (fake *FakeChecker) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeChecker) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ muxt.Checker = new(FakeChecker)
